const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, 'lib', 'i18n');

const translations = {
  hi: {
    cropCalendar: "फसल कैलेंडर",
    pestAdvisory: "कीट और रोग प्रबंधन",
    pestAdvisoryDesc: "हाइपर-लोकल मौसम और फसल चक्र के आधार पर फसल सुरक्षा के लिए रीयल-टाइम सलाह।",
    fieldInputCenter: "फील्ड इनपुट सेंटर",
    selectYourCrop: "अपनी फसल चुनें",
    selectCrop: "फसल चुनें",
    weatherCondition: "मौसम की स्थिति",
    fetchAdvisory: "रीयल-टाइम सलाह प्राप्त करें",
    analyzingEnv: "पर्यावरण का विश्लेषण...",
    criticalAlertsFor: "महत्वपूर्ण अलर्ट",
    aiConfidence: "AI आत्मविश्वास",
    lastScan: "पिछला स्कैन",
    targetPests: "लक्षित कीट",
    potentialDiseases: "संभावित रोग",
    risk: "जोखिम",
    expertAiStrategy: "विशेषज्ञ AI रणनीति",
    preventionStrategy: "रोकथाम रणनीति",
    organicTreatment: "जैविक उपचार",
    riskAssessmentSummary: "जोखिम मूल्यांकन सारांश",
    pestsIdentified: "कीटों की पहचान",
    diseaseRisks: "रोग जोखिम",
    totalThreats: "कुल खतरे",
    criticalAlerts: "महत्वपूर्ण अलर्ट",
    noAnalysisResults: "कोई विश्लेषण परिणाम नहीं",
    selectCropDesc: "रीयल-टाइम कीट प्रबंधन डेटा प्राप्त करने के लिए कृपया अपनी फसल और वर्तमान मौसम की स्थिति चुनें।",
    hotAndDry: "गर्म और शुष्क",
    humidAndRainy: "नम और बरसात",
    coolAndMoist: "ठंडा और नम",
    tomatoWithScript: "टमाटर (Tomato)",
    cottonWithScript: "कपास (Cotton)",
    maizeWithScript: "मक्का (Maize)",
    wheatWithScript: "गेहूं (Wheat)",
    nitrogens: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassiums: "पोटेशियम (K)",
    phLevel: "pH स्तर",
    moistureContent: "नमी की मात्रा",
    analyzingSoil: "मिट्टी का विश्लेषण...",
    analyzeSoil: "मिट्टी का विश्लेषण करें",
    analysisResults: "विश्लेषण परिणाम",
    soilFertility: "मिट्टी की उर्वरता",
    level: "स्तर",
    recommendedCrop: "अनुशंसित फसल",
    highSuitability: "उच्च उपयुक्तता",
    disclaimer: "अस्वीकरण",
    disclaimerText: "सुझाव क्षेत्रीय ऐतिहासिक डेटा पर आधारित हैं। हम सटीक योजना के लिए पेशेवर मिट्टी परीक्षण की सलाह देते हैं।",
    smartCropRecommendation: "स्मार्ट फसल अनुशंसा",
    smartCropRecommendationDesc: "मिट्टी के स्वास्थ्य के आधार पर इष्टतम फसल चयन के लिए AI-संचालित अंतर्दृष्टि।",
    waitingForDetails: "खेत के विवरण की प्रतीक्षा है",
    weatherForecast: "मौसम पूर्वानुमान",
    syncingSatellites: "उपग्रहों के साथ तालमेल बिठाना...",
    temperatureTrend: "तापमान का रुझान",
    precipitation: "वर्षा",
    windConditions: "हवा की स्थिति",
    dailyBreakdown: "दैनिक विवरण",
    tempAndCondPeriod: "प्रति अवधि तापमान और स्थिति",
    agriculturalInsight: "कृषि अंतर्दृष्टि",
    detailedPdfReport: "विस्तृत PDF रिपोर्ट",
    tryAgain: "फिर से प्रयास करें",
    establishCoordinateLock: "निर्देशांक लॉक स्थापित करें",
    syncCoordinates: "निर्देशांक सिंक करें",
    morning: "सुबह",
    afternoon: "दोपहर",
    evening: "शाम",
    night: "रात",
    today: "आज",
    kisanSupport: "किसान सहायता",
    checkCropHealth: "🌿 फसल स्वास्थ्य की जाँच करें",
    identifyFromLeaf: "1 पत्ते से समस्याओं की पहचान करें",
    scanFarmAreaOption: "🌾 खेत क्षेत्र को स्कैन करें",
    scanFieldArea: "पूरे खेत क्षेत्र को स्कैन करें",
    smartFarmingTools: "स्मार्ट खेती उपकरण",
    soilPredictorAI: "मिट्टी प्रिडिक्टर AI",
    thriveTogether: "एक साथ आगे बढ़ें",
    home: "होम",
    weather: "मौसम",
    market: "बाजार",
    aiChat: "AI चैट",
    pestsAndDisease: "कीट और रोग",
    schemes: "योजनाएं",
    seedsStore: "बीज स्टोर",
    calendar: "कैलेंडर",
    rentTractor: "ट्रैक्टर किराया",
    supportPortal: "सहायता पोर्टल",
    more: "अधिक",
  },
  te: {
    cropCalendar: "పంట క్యాలెండర్",
    pestAdvisory: "కీటకాలు మరియు వ్యాధుల నిర్వహణ",
    pestAdvisoryDesc: "స్థానిక వాతావరణం మరియు పంట చక్రాల ఆధారంగా పంట రక్షణ కోసం నిజ-సమయ సలహా.",
    fieldInputCenter: "ఫీల్డ్ ఇన్‌పుట్ సెంటర్",
    selectYourCrop: "మీ పంటను ఎంచుకోండి",
    selectCrop: "పంటను ఎంచుకోండి",
    weatherCondition: "వాతావరణ పరిస్థితి",
    fetchAdvisory: "నిజ-సమయ సలహాను పొందండి",
    analyzingEnv: "పర్యావరణాన్ని విశ్లేషిస్తోంది...",
    criticalAlertsFor: "కీలక హెచ్చరికలు",
    aiConfidence: "AI విశ్వాసం",
    lastScan: "చివరి స్కాన్",
    targetPests: "లక్షిత కీటకాలు",
    potentialDiseases: "సంభావ్య వ్యాధులు",
    risk: "ప్రమాదం",
    expertAiStrategy: "నిపుణుల AI వ్యూహం",
    preventionStrategy: "నివారణ వ్యూహం",
    organicTreatment: "సేంద్రియ చికిత్స",
    riskAssessmentSummary: "ప్రమాద అంచనా సారాంశం",
    pestsIdentified: "గుర్తించిన కీటకాలు",
    diseaseRisks: "వ్యాధి ప్రమాదాలు",
    totalThreats: "మొత్తం ముప్పులు",
    criticalAlerts: "కీలక హెచ్చరికలు",
    noAnalysisResults: "విశ్లేషణ ఫలితాలు లేవు",
    selectCropDesc: "నిజ-సమయ కీటక నిర్వహణ డేటాను పొందడానికి దయచేసి మీ పంట మరియు ప్రస్తుత వాతావరణ పరిస్థితులను ఎంచుకోండి.",
    hotAndDry: "వేడి మరియు పొడి",
    humidAndRainy: "తేమ మరియు వర్షం",
    coolAndMoist: "చల్లని మరియు తేమ",
    tomatoWithScript: "టమోటా (తక్కాళి / टमाटर)",
    cottonWithScript: "పత్తి (పత్తి / कपास)",
    maizeWithScript: "మొక్కజొన్న (మొక్కజొన్న / मक्का)",
    wheatWithScript: "గోధుమ (గోధుమ / गेहूं)",
    nitrogens: "నత్రజని (N)",
    phosphorus: "భాస్వరం (P)",
    potassiums: "పొటాషియం (K)",
    phLevel: "pH స్థాయి",
    moistureContent: "తేమ శాతం",
    analyzingSoil: "మట్టిని విశ్లేషిస్తోంది...",
    analyzeSoil: "మట్టిని విశ్లేషించండి",
    analysisResults: "విశ్లేషణ ఫలితాలు",
    soilFertility: "మట్టి సారవంతం",
    level: "స్థాయి",
    recommendedCrop: "సిఫార్సు చేయబడిన పంట",
    highSuitability: "అధిక అనుకూలత",
    disclaimer: "నిరాకరణ",
    disclaimerText: "సూచనలు ప్రాంతీయ చారిత్రక డేటాపై ఆధారపడి ఉంటాయి. ఖచ్చితమైన ప్రణాళిక కోసం వృత్తిపరమైన మట్టి పరీక్షను మేము సిఫార్సు చేస్తున్నాము.",
    smartCropRecommendation: "స్మార్ట్ పంట సిఫార్సు",
    smartCropRecommendationDesc: "మట్టి ఆరోగ్యం ఆధారంగా సరైన పంట ఎంపిక కోసం AI అంతర్దృష్టులు.",
    waitingForDetails: "ఫాం వివరాల కోసం వేచి ఉంది",
    weatherForecast: "వాతావరణ సూచన",
    syncingSatellites: "శాటిలైట్లతో అనుసంధానిస్తోంది...",
    temperatureTrend: "ఉష్ణోగ్రత ధోరణి",
    precipitation: "వర్షపాతం",
    windConditions: "గాలి పరిస్థితులు",
    dailyBreakdown: "రోజువారీ వివరాలు",
    tempAndCondPeriod: "సమయానుకూల ఉష్ణోగ్రత మరియు పరిస్థితులు",
    agriculturalInsight: "వ్యవసాయ అంతర్దృష్టి",
    detailedPdfReport: "వివరమైన PDF నివేదిక",
    tryAgain: "మళ్ళీ ప్రయత్నించండి",
    establishCoordinateLock: "కోఆర్డినేట్ లాక్ ఏర్పాటు చేయండి",
    syncCoordinates: "కోఆర్డినేట్లను సింక్ చేయండి",
    morning: "ఉదయం",
    afternoon: "మధ్యాహ్నం",
    evening: "సాయంత్రం",
    night: "రాత్రి",
    today: "ఈరోజు",
    kisanSupport: "కిసాన్ మద్దతు",
    checkCropHealth: "🌿 పంట ఆరోగ్యాన్ని తనిఖీ చేయండి",
    identifyFromLeaf: "1 ఆకు నుండి సమస్యలను గుర్తించండి",
    scanFarmAreaOption: "🌾 వ్యవసాయ ప్రాంతాన్ని స్కాన్ చేయండి",
    scanFieldArea: "మొత్తం పొలం ప్రాంతాన్ని స్కాన్ చేయండి",
    smartFarmingTools: "స్మార్ట్ ఫార్మింగ్ టూల్స్",
    soilPredictorAI: "మట్టి ప్రిడిక్టర్ AI",
    thriveTogether: "కలిసి అభివృద్ధి చెందుదాం",
    home: "హోమ్",
    weather: "వాతావరణం",
    market: "మార్కెట్",
    aiChat: "AI చాట్",
    pestsAndDisease: "కీటకాలు మరియు వ్యాధులు",
    schemes: "పథకాలు",
    seedsStore: "విత్తనాల స్టోర్",
    calendar: "క్యాలెండర్",
    rentTractor: "ట్రాక్టర్ అద్దె",
    supportPortal: "మద్దతు పోర్టల్",
    more: "మరిన్ని",
  },
  ta: {
    cropCalendar: "பயிர் காலண்டர்",
    pestAdvisory: "பூச்சி ஆலோசனை",
    kisanSupport: "கிசான் ஆதரவு",
    checkCropHealth: "🌿 பயிர் ஆரோக்கியத்தை சரிபார்க்கவும்",
    identifyFromLeaf: "1 இலையிலிருந்து சிக்கல்களைக் கண்டறியவும்",
    scanFarmAreaOption: "🌾 பண்ணை பகுதியை ஸ்கேன் செய்யவும்",
    scanFieldArea: "முழு வயல் பகுதியையும் ஸ்கேன் செய்யவும்",
    smartFarmingTools: "ஸ்மார்ட் விவசாயக் கருவிகள்",
    soilPredictorAI: "மண் கணிப்பான் AI",
    thriveTogether: "ஒன்றாக செழிப்போம்",
    home: "முகப்பு",
    weather: "வானிலை",
    market: "சந்தை",
    aiChat: "AI அரட்டை",
    pestsAndDisease: "பூச்சிகள் மற்றும் நோய்கள்",
    schemes: "திட்டங்கள்",
    seedsStore: "விதை கடை",
    calendar: "காலண்டர்",
    rentTractor: "டிராக்டர் வாடகை",
    supportPortal: "ஆதரவு போர்டல்",
    more: "மேலும்",
  },
  kn: {
    cropCalendar: "ಬೆಳೆ ಕ್ಯಾಲೆಂಡರ್",
    pestAdvisory: "ಕೀಟ ಸಲಹೆ",
    kisanSupport: "ಕಿಸಾನ್ ಬೆಂಬಲ",
    checkCropHealth: "🌿 ಬೆಳೆ ಆರೋಗ್ಯ ಪರಿಶೀಲಿಸಿ",
    identifyFromLeaf: "1 ಎಲೆಯಿಂದ ಸಮಸ್ಯೆಗಳನ್ನು ಗುರುತಿಸಿ",
    scanFarmAreaOption: "🌾 ಕೃಷಿ ಪ್ರದೇಶವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    scanFieldArea: "ಸಂಪೂರ್ಣ ಹೊಲದ ಪ್ರದೇಶವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    smartFarmingTools: "ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮಿಂಗ್ ಪರಿಕರಗಳು",
    soilPredictorAI: "ಮಣ್ಣಿನ ಪ್ರಿಡಿಕ್ಟರ್ AI",
    thriveTogether: "ಒಟ್ಟಾಗಿ ಅಭಿವೃದ್ಧಿ ಹೊಂದೋಣ",
    home: "ಮನೆ",
    weather: "ಹವಾಮಾನ",
    market: "ಮಾರುಕಟ್ಟೆ",
    aiChat: "AI ಚಾಟ್",
    pestsAndDisease: "ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳು",
    schemes: "ಯೋಜನೆಗಳು",
    seedsStore: "ಬೀಜಗಳ ಅಂಗಡಿ",
    calendar: "ಕ್ಯಾಲೆಂಡರ್",
    rentTractor: "ಟ್ರಾಕ್ಟರ್ ಬಾಡಿಗೆ",
    supportPortal: "ಬೆಂಬಲ ಪೋರ್ಟಲ್",
    more: "ಇನ್ನಷ್ಟು",
  },
  ml: {
    cropCalendar: "വിള കലണ്ടർ",
    pestAdvisory: "കീട ഉപദേശം",
    kisanSupport: "കിസാൻ പിന്തുണ",
    checkCropHealth: "🌿 വിള ആരോഗ്യം പരിശോധിക്കുക",
    identifyFromLeaf: "1 ഇലയിൽ നിന്ന് പ്രശ്നങ്ങൾ തിരിച്ചറിയുക",
    scanFarmAreaOption: "🌾 ഫാം ഏരിയ സ്കാൻ ചെയ്യുക",
    scanFieldArea: "മുഴുവൻ ഫീൽഡ് ഏരിയയും സ്കാൻ ചെയ്യുക",
    smartFarmingTools: "സ്മാർട്ട് ഫാമിംഗ് ടൂളുകൾ",
    soilPredictorAI: "സോയിൽ പ്രെഡിക്റ്റർ AI",
    thriveTogether: "ഒന്നിച്ചു വളരാം",
    home: "ഹോം",
    weather: "കാലാവസ്ഥ",
    market: "മാർക്കറ്റ്",
    aiChat: "AI ചാറ്റ്",
    pestsAndDisease: "കീടങ്ങളും രോഗങ്ങളും",
    schemes: "പദ്ധതികൾ",
    seedsStore: "വിത്ത് സ്റ്റോർ",
    calendar: "കലണ്ടർ",
    rentTractor: "ട്രാക്ടർ വാടക",
    supportPortal: "പിന്തുണ പോർട്ടൽ",
    more: "കൂടുതൽ",
  },
  bn: {
    cropCalendar: "ফসলের ক্যালেন্ডার",
    pestAdvisory: "কীটপতঙ্গ পরামর্শ",
    kisanSupport: "কিষাণ সহায়তা",
    checkCropHealth: "🌿 ফসলের স্বাস্থ্য পরীক্ষা করুন",
    identifyFromLeaf: "১টি পাতা থেকে সমস্যা চিহ্নিত করুন",
    scanFarmAreaOption: "🌾 খামারের এলাকা স্ক্যান করুন",
    scanFieldArea: "সম্পূর্ণ মাঠ এলাকা স্ক্যান করুন",
    smartFarmingTools: "স্মার্ট ফার্মিং টুলস",
    soilPredictorAI: "মাটি প্রেডিক্টর AI",
    thriveTogether: "একসাথে উন্নতি করি",
    home: "হোম",
    weather: "আবহাওয়া",
    market: "বাজার",
    aiChat: "AI চ্যাট",
    pestsAndDisease: "কীটপতঙ্গ এবং রোগ",
    schemes: "প্রকল্প",
    seedsStore: "বীজ স্টোর",
    calendar: "ক্যালেন্ডার",
    rentTractor: "ট্রাক্টর ভাড়া",
    supportPortal: "সহায়তা পোর্টাল",
    more: "আরও",
  },
  mr: {
    cropCalendar: "पीक कॅलेंडर",
    pestAdvisory: "कीड सल्ला",
    kisanSupport: "किसान मदत",
    checkCropHealth: "🌿 पीक आरोग्य तपासा",
    identifyFromLeaf: "१ पानावरून समस्या ओळखा",
    scanFarmAreaOption: "🌾 शेती क्षेत्र स्कॅन करा",
    scanFieldArea: "संपूर्ण शेत क्षेत्र स्कॅन करा",
    smartFarmingTools: "ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮಿಂಗ್ ಪರಿಕರಗಳು",
    soilPredictorAI: "माती प्रेडिक्टर AI",
    thriveTogether: "एकत्र समृद्ध होऊया",
    home: "होम",
    weather: "हवामान",
    market: "बाजार",
    aiChat: "AI चॅट",
    pestsAndDisease: "कीड आणि रोग",
    schemes: "योजना",
    seedsStore: "बियाणे दुकान",
    calendar: "कॅलेंडर",
    rentTractor: "ट्रॅक्टर भाड्याने",
    supportPortal: "मदत पोर्टल",
    more: "अधिक",
  },
  pa: {
    cropCalendar: "ਫਸਲ ਕੈਲੰਡਰ",
    pestAdvisory: "ਕੀੜੇ ਦੀ ਸਲਾਹ",
    kisanSupport: "ਕਿਸਾਨ ਸਹਾਇਤਾ",
    checkCropHealth: "🌿 ਫਸਲ ਦੀ ਸਿਹਤ ਦੀ ਜਾਂਚ ਕਰੋ",
    identifyFromLeaf: "1 ਪੱਤੇ ਤੋਂ ਸਮੱਸਿਆਵਾਂ ਦੀ ਪਛਾਣ ਕਰੋ",
    scanFarmAreaOption: "🌾 ਫਾਰਮ ਖੇਤਰ ਨੂੰ ਸਕੈਨ ਕਰੋ",
    scanFieldArea: "ਪੂਰੇ ਖੇਤ ਖੇਤਰ ਨੂੰ ਸਕੈਨ ਕਰੋ",
    smartFarmingTools: "ਸਮਾਰਟ ਫਾਰਮਿੰਗ ਟੂਲਸ",
    soilPredictorAI: "ਮਿੱਟੀ ਪ੍ਰੀਡਿਕਟਰ AI",
    thriveTogether: "ਮਿਲ ਕੇ ਤਰੱਕੀ ਕਰੀਏ",
    home: "ਹੋਮ",
    weather: "ਮੌਸਮ",
    market: "ਬਾਜ਼ਾਰ",
    aiChat: "AI ਚੈਟ",
    pestsAndDisease: "ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀਆਂ",
    schemes: "ਸਕੀਮਾਂ",
    seedsStore: "ਬੀਜ ਸਟੋਰ",
    calendar: "ਕੈਲੰਡਰ",
    rentTractor: "ਟਰੈਕਟਰ ਕਿਰਾਇਆ",
    supportPortal: "ਸਹਾਇਤਾ ਪੋਰਟਲ",
    more: "ਹੋਰ",
  },
  gu: {
    cropCalendar: "પાક કેલેન્ડર",
    pestAdvisory: "જીવાત સલાહ",
    kisanSupport: "કિસાન સહાય",
    checkCropHealth: "🌿 પાક આરોગ્ય તપાસો",
    identifyFromLeaf: "1 પાંદડા પરથી સમસ્યાઓ ઓળખો",
    scanFarmAreaOption: "🌾 ખેતરનો વિસ્તાર સ્કેન કરો",
    scanFieldArea: "આખા ખેતરનો વિસ્તાર સ્કેન કરો",
    smartFarmingTools: "સ્માર્ટ ફાર્મિંગ ટૂલ્સ",
    soilPredictorAI: "જમીન અનુમાનક AI",
    thriveTogether: "સાથે મળીને પ્રગતિ કરીએ",
    home: "હોમ",
    weather: "હવામાન",
    market: "બજાર",
    aiChat: "AI ચેટ",
    pestsAndDisease: "જીવાત અને રોગ",
    schemes: "યોજનાઓ",
    seedsStore: "બીજ સ્ટોર",
    calendar: "કેલેન્ડર",
    rentTractor: "ટ્રેક્ટર ભાડું",
    supportPortal: "સહાય પોર્ટલ",
    more: "વધુ",
  }
};

Object.keys(translations).forEach(lang => {
  const filePath = path.join(i18nDir, lang + '.ts');
  if (fs.existsSync(filePath)) {
    let content = fs.readFileSync(filePath, 'utf8');
    const langData = translations[lang];
    
    Object.keys(langData).forEach(key => {
      const entry = `    ${key}: "${langData[key]}",`;
      if (!content.includes(`${key}:`)) {
        const lastBraceIndex = content.lastIndexOf('}');
        if (lastBraceIndex !== -1) {
          content = content.slice(0, lastBraceIndex) + entry + '\n' + content.slice(lastBraceIndex);
        }
      } else {
        const regex = new RegExp(`${key}:\\s*".*?"`, 'g');
        content = content.replace(regex, `${key}: "${langData[key]}"`);
      }
    });
    
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Updated ${lang}.ts with more keys`);
  }
});
