import os
import re

# New keys and translations for all 10 languages
new_keys = {
    "English": {
        "seasonalCropGuide": "Seasonal Crop Guide",
        "seasonalCropGuideDesc": "Discover which crops are best for each season.",
        "kharifCrops": "Kharif Crops",
        "kharifCropsDesc": "Sown in June-July, Harvested in Sept-Oct. (e.g., Rice, Cotton, Maize)",
        "rabiCrops": "Rabi Crops",
        "rabiCropsDesc": "Sown in Oct-Dec, Harvested in Mar-April. (e.g., Wheat, Mustard, Gram)",
        "zaidCrops": "Zaid Crops",
        "zaidCropsDesc": "Sown in Mar-June, Short duration summer crops. (e.g., Watermelon, Cucumber)",
        "waterManagementGuide": "Water Management Guide",
        "waterManagementDesc": "Modern irrigation and water saving techniques.",
        "dripIrrigation": "Drip Irrigation",
        "dripIrrigationDesc": "Direct root watering, saves up to 50% water.",
        "sprinklerIrrigation": "Sprinkler Irrigation",
        "sprinklerIrrigationDesc": "Mimics rainfall, ideal for uniform coverage.",
        "rainwaterHarvesting": "Rainwater Harvesting",
        "rainwaterHarvestingDesc": "Collecting rain for future agricultural use.",
        "fertilizerNutrientGuide": "Fertilizer & Nutrient Guide",
        "fertilizerNutrientDesc": "Optimal nutrition for high-yield farming.",
        "npkBalance": "NPK Balance",
        "npkBalanceDesc": "Understanding Nitrogen, Phosphorus, and Potassium needs.",
        "nutrientDeficiency": "Nutrient Deficiency",
        "nutrientDeficiencyDesc": "Identify and fix common plant nutrient issues.",
        "farmMachineryGuide": "Farm Machinery Guide",
        "farmMachineryDesc": "Operational instructions for modern farm equipment.",
        "seedDrillInstr": "Seed Drill Instructions",
        "seedDrillDesc": "Precise seed placement at uniform depth.",
        "harvesterInstr": "Harvester Instructions",
        "harvesterDesc": "Efficient reaping and threshing in one step.",
        "sprayerInstr": "Sprayer Instructions",
        "sprayerDesc": "Uniform application of pesticides and fertilizers.",
        "extremeWeatherAlerts": "Extreme Weather Alerts",
        "extremeWeatherDesc": "Real-time alerts for storms, heatwaves, and frost.",
        "weatherAlertTitle": "Action Required!",
        "heatwaveWarning": "Critical Heat Warning: Keep soil moist.",
        "frostWarning": "Frost Alert: Protect young seedlings.",
        "storagePostHarvest": "Storage & Post-Harvest Guide",
        "storagePostHarvestDesc": "Maximize profits with proper storage.",
        "grainStorage": "Grain Storage",
        "grainStorageDesc": "Modern silos and hermetic bags to prevent pests.",
        "coldStorage": "Cold Storage",
        "coldStorageDesc": "Extend shelf life for fruits and vegetables.",
        "nearbyAgriServices": "Nearby Agri Services",
        "nearbyServicesDesc": "Find tractor repair, seed stores, and mandis.",
        "cropVarietyDatabase": "Crop Variety Database",
        "cropVarietyDesc": "Detailed database of high-yield crop varieties.",
        "farmTaskManager": "Farm Task Manager",
        "farmTaskDesc": "Organize your daily and seasonal farm activities.",
        "mspGovtPrice": "MSP & Govt Price Info",
        "mspGovtPriceDesc": "Current Minimum Support Prices for your crops.",
        "mspWheat": "MSP Wheat (2024-25)",
        "mspPaddy": "MSP Paddy (2024-25)",
        "mspCotton": "MSP Cotton (2024-25)",
        "agriVideoLearning": "Agri Video Learning Center",
        "agriVideoDesc": "Master farming with expert video tutorials.",
        "subsidyTracker": "Agriculture Subsidy Tracker",
        "subsidyTrackerDesc": "Follow your application and payment status.",
        "applicationStatus": "Application Status",
        "paymentReceived": "Payment Received"
    },
    "Hindi": {
        "seasonalCropGuide": "मौसमी फसल गाइड",
        "seasonalCropGuideDesc": "जानें कि प्रत्येक मौसम के लिए कौन सी फसलें सबसे अच्छी हैं।",
        "kharifCrops": "खरीफ फसलें",
        "kharifCropsDesc": "जून-जुलाई में बोई गई, सितंबर-अक्टूबर में काटी गई। (जैसे चावल, कपास, मक्का)",
        "rabiCrops": "रबी फसलें",
        "rabiCropsDesc": "अक्टूबर-दिसंबर में बोई गई, मार्च-अप्रैल में काटी गई। (जैसे गेहूं, सरसों, चना)",
        "zaidCrops": "जायद फसलें",
        "zaidCropsDesc": "मार्च-जून में बोई गई, अल्पकालिक गर्मी की फसलें। (जैसे तरबूज, खीरा)",
        "waterManagementGuide": "जल प्रबंधन गाइड",
        "waterManagementDesc": "आधुनिक सिंचाई और जल बचत तकनीक।",
        "dripIrrigation": "ड्रिप सिंचाई",
        "dripIrrigationDesc": "सीधे जड़ में पानी, 50% तक पानी बचाता है।",
        "sprinklerIrrigation": "स्प्रिंकलर सिंचाई",
        "sprinklerIrrigationDesc": "बारिश की नकल करता है, समान कवरेज के लिए आदर्श।",
        "rainwaterHarvesting": "वर्षा जल संचयन",
        "rainwaterHarvestingDesc": "भविष्य के कृषि उपयोग के लिए बारिश का पानी इकट्ठा करना।",
        "fertilizerNutrientGuide": "उर्वरक एवं पोषक तत्व गाइड",
        "fertilizerNutrientDesc": "उच्च उपज वाली खेती के लिए इष्टतम पोषण।",
        "npkBalance": "एनपीके संतुलन",
        "npkBalanceDesc": "नाइट्रोजन, फास्फोरस और पोटेशियम की जरूरतों को समझना।",
        "nutrientDeficiency": "पोषक तत्वों की कमी",
        "nutrientDeficiencyDesc": "पौधों के पोषक तत्वों के सामान्य मुद्दों को पहचानें और ठीक करें।",
        "farmMachineryGuide": "कृषि मशीनरी गाइड",
        "farmMachineryDesc": "आधुनिक कृषि उपकरणों के लिए संचालन निर्देश।",
        "seedDrillInstr": "सीड ड्रिल निर्देश",
        "seedDrillDesc": "समान गहराई पर सटीक बीज नियुक्ति।",
        "harvesterInstr": "हार्वेस्टर निर्देश",
        "harvesterDesc": "एक ही चरण में कुशल कटाई और गहाई।",
        "sprayerInstr": "स्प्रेयर निर्देश",
        "sprayerDesc": "कीटनाशकों और उर्वरकों का समान प्रयोग।",
        "extremeWeatherAlerts": "अत्यधिक मौसम अलर्ट",
        "extremeWeatherDesc": "तूफान, लू और पाले के लिए रीयल-टाइम अलर्ट।",
        "weatherAlertTitle": "कार्रवाई आवश्यक!",
        "heatwaveWarning": "गंभीर लू की चेतावनी: मिट्टी को नम रखें।",
        "frostWarning": "पाले की चेतावनी: युवा पौधों को बचाएं।",
        "storagePostHarvest": "भंडारण एवं कटाई के बाद गाइड",
        "storagePostHarvestDesc": "उचित भंडारण के साथ लाभ अधिकतम करें।",
        "grainStorage": "अनाज भंडारण",
        "grainStorageDesc": "कीटों से बचाने के लिए आधुनिक सिलो और हवादार बैग।",
        "coldStorage": "कोल्ड स्टोरेज",
        "coldStorageDesc": "फलों और सब्जियों के शेल्फ जीवन का विस्तार करें।",
        "nearbyAgriServices": "निकटतम कृषि सेवाएं",
        "nearbyServicesDesc": "ट्रैक्टर मरम्मत, बीज भंडार और मंडियां खोजें।",
        "cropVarietyDatabase": "फसल किस्म डेटाबेस",
        "cropVarietyDesc": "उच्च उपज वाली फसल किस्मों का विस्तृत डेटाबेस।",
        "farmTaskManager": "कृषि कार्य प्रबंधक",
        "farmTaskDesc": "अपनी दैनिक और मौসमी कृषि गतिविधियों को व्यवस्थित करें।",
        "mspGovtPrice": "एमएसपी एवं सरकारी मूल्य जानकारी",
        "mspGovtPriceDesc": "आपकी फसलों के लिए वर्तमान न्यूनतम समर्थन मूल्य।",
        "mspWheat": "एमएसपी गेहूं (2024-25)",
        "mspPaddy": "एमएसपी धान (2024-25)",
        "mspCotton": "एमएसपी कपास (2024-25)",
        "agriVideoLearning": "कृषि वीडियो लर्निंग सेंटर",
        "agriVideoDesc": "विशेषज्ञ वीडियो ट्यूटोरियल के साथ खेती में महारत हासिल करें।",
        "subsidyTracker": "कृषि सब्सिडी ट्रैकर",
        "subsidyTrackerDesc": "अपने आवेदन और भुगतान की स्थिति का पालन करें।",
        "applicationStatus": "आवेदन की स्थिति",
        "paymentReceived": "भुगतान प्राप्त हुआ"
    },
    "Telugu": {
        "seasonalCropGuide": "సీజనల్ పంటల గైడ్",
        "seasonalCropGuideDesc": "ప్రతి సీజన్‌కు ఏ పంటలు ఉత్తమమో కనుగొనండి.",
        "kharifCrops": "ఖరీఫ్ పంటలు",
        "kharifCropsDesc": "జూన్-జులైలో విత్తినవి, సెప్టెంబర్-అక్టోబర్‌లో కోసినవి. (ఉదా. వరి, పత్తి, మొక్కజొన్న)",
        "rabiCrops": "రబీ పంటలు",
        "rabiCropsDesc": "అక్టోబర్-డిసెంబర్‌లో విత్తినవి, మార్చి-ఏప్రిల్‌లో కోసినవి. (ఉదా. గోధుమ, ఆవాలు, శనగలు)",
        "zaidCrops": "జైద్ పంటలు",
        "zaidCropsDesc": "మార్చి-జూన్ లో విత్తినవి, స్వల్పకాలిక వేసవి పంటలు. (ఉదా. పుచ్చకాయ, దోసకాయ)",
        "waterManagementGuide": "నీటి యాజమాన్య గైడ్",
        "waterManagementDesc": "ఆధునిక సాగు మరియు నీటి పొదుపు పద్ధతులు.",
        "dripIrrigation": "బిందు సేద్యం (డ్రిప్)",
        "dripIrrigationDesc": "నేరుగా వేర్లకు నీరు, 50% వరకు నీటి పొదుపు.",
        "sprinklerIrrigation": "స్ప్రింక్లర్ సేద్యం",
        "sprinklerIrrigationDesc": "వర్షంలా నీటిని చల్లుతుంది, సమాన సాగుకు అనుకూలం.",
        "rainwaterHarvesting": "వర్షపు నీటి సంరక్షణ",
        "rainwaterHarvestingDesc": "భవిష్యత్ అవసరాల కోసం వర్షపు నీటిని సేకరించడం.",
        "fertilizerNutrientGuide": "ఎరువులు & పోషకాల గైడ్",
        "fertilizerNutrientDesc": "అధిక దిగుబడి కోసం సరైన పోషణ.",
        "npkBalance": "NPK సంతులనం",
        "npkBalanceDesc": "నత్రజని, భాస్వరం మరియు పొటాషియం అవసరాలను అర్థం చేసుకోవడం.",
        "nutrientDeficiency": "పోషక లోపాలు",
        "nutrientDeficiencyDesc": "సాధారణ మొక్కల పోషక సమస్యలను గుర్తించి సరిచేయండి.",
        "farmMachineryGuide": "వ్యవసాయ యంత్రాల గైడ్",
        "farmMachineryDesc": "ఆధునిక వ్యవసాయ పరికరాల వినియోగ సూచనలు.",
        "seedDrillInstr": "సీడ్ డ్రిల్ సూచనలు",
        "seedDrillDesc": "సరైన లోతులో ఖచ్చితమైన విత్తన విత్తనం.",
        "harvesterInstr": "హార్వెస్టర్ సూచనలు",
        "harvesterDesc": "ఒకేసారి కోత మరియు నూర్పిడి ప్రక్రియ.",
        "sprayerInstr": "స్ప్రేయర్ సూచనలు",
        "sprayerDesc": "క్రిమిసంహారకాలు మరియు ఎరువుల సమాన పిచికారీ.",
        "extremeWeatherAlerts": "వాతావరణ హెచ్చరికలు",
        "extremeWeatherDesc": "తుఫానులు, ఎండలు మరియు మంచు కోసం ఎప్పటికప్పుడు హెచ్చరికలు.",
        "weatherAlertTitle": "చర్య అవసరం!",
        "heatwaveWarning": "తీవ్రమైన ఎండల హెచ్చరిక: నేలను తేమగా ఉంచండి.",
        "frostWarning": "మంచు హెచ్చరిక: చిన్న మొక్కలను రక్షించండి.",
        "storagePostHarvest": "నిల్వ & కోత అనంతర గೈడ్",
        "storagePostHarvestDesc": "సరైన నిల్వతో లాభాలను పెంచుకోండి.",
        "grainStorage": "ధాన్యపు నిల్వ",
        "grainStorageDesc": "పురుగుల నుండి రక్షించడానికి ఆధునిక గిడ్డంగులు.",
        "coldStorage": "కోల్డ్ స్టోరేజ్",
        "coldStorageDesc": "పండ్లు మరియు కూరగాయల నిల్వ కాలాన్ని పెంచండి.",
        "nearbyAgriServices": "సమీప వ్యవసాయ సేవలు",
        "nearbyServicesDesc": "ట్రాక్టర్ మరమ్మతులు, విత్తన దుకాణాలు మరియు మండిలను కనుగొనండి.",
        "cropVarietyDatabase": "పంట రకాల డేటాబేస్",
        "cropVarietyDesc": "అధిక దిగుబడి ఇచ్చే పంట రకాల పూర్తి వివరాలు.",
        "farmTaskManager": "వ్యవసాయ పనుల నిర్వాహకుడు",
        "farmTaskDesc": "మీ రోజువారీ మరియు సీజనల్ వ్యవసాయ పనులను ప్లాన్ చేయండి.",
        "mspGovtPrice": "MSP & ప్రభుత్వ ధరల సమాచారం",
        "mspGovtPriceDesc": "మీ పంటలకు ప్రస్తుత కనీస మద్దతు ధరలు.",
        "mspWheat": "MSP గోధుమ (2024-25)",
        "mspPaddy": "MSP వరి (2024-25)",
        "mspCotton": "MSP పత్తి (2024-25)",
        "agriVideoLearning": "వ్యవసాయ వీడియో లెర్నింగ్ సెంటర్",
        "agriVideoDesc": "నిపుణుల వీడియోల ద్వారా వ్యవసాయంలో పట్టు సాధించండి.",
        "subsidyTracker": "వ్యవసాయ సబ్సిడీ ట్రాకర్",
        "subsidyTrackerDesc": "మీ దరఖాస్తు మరియు చెల్లింపు స్థితిని తెలుసుకోండి.",
        "applicationStatus": "దరఖాస్తు స్థితి",
        "paymentReceived": "చెల్లింపు అందింది"
    },
    "Tamil": {
        "seasonalCropGuide": "பருவகால பயிர் வழிகாட்டி",
        "seasonalCropGuideDesc": "ஒவ்வொரு பருவத்திற்கும் எந்தப் பயிர்கள் சிறந்தது என்பதைக் கண்டறியவும்.",
        "kharifCrops": "காரீப் பயிர்கள்",
        "kharifCropsDesc": "ஜூன்-ஜூலையில் விதைக்கப்பட்டு, செப்டம்பர்-அக்டோபரில் அறுவடை செய்யப்படுகிறது. (எ.கா. நெல், பருத்தி, சோளம்)",
        "rabiCrops": "ரபி பயிர்கள்",
        "rabiCropsDesc": "அக்டோபர்-டிசம்பரில் விதைக்கப்பட்டு, மார்ச்-ஏப்ரலில் அறுவடை செய்யப்படுகிறது. (எ.கா. கோதுமை, கடுகு, கொண்டக்கடலை)",
        "zaidCrops": "ஜயத் பயிர்கள்",
        "zaidCropsDesc": "மார்ச்-ஜூன் மாதங்களில் விதைக்கப்படும் குறுகிய கால கோடை பயிர்கள். (எ.கா. தர்பூசணி, வெள்ளரி)",
        "waterManagementGuide": "நீர் மேலாண்மை வழிகாட்டி",
        "waterManagementDesc": "நவீன நீர்ப்பாசனம் மற்றும் நீர் சேமிப்பு தொழில்நுட்பங்கள்.",
        "dripIrrigation": "சொட்டு நீர் பாசனம்",
        "dripIrrigationDesc": "நேரடி வேர் நீர்ப்பாசனம், 50% வரை நீர் சேமிப்பு.",
        "sprinklerIrrigation": "தெளிப்பு நீர் பாசனம்",
        "sprinklerIrrigationDesc": "மழையைப் போன்ற பாசனம், சமமான பரப்புக்கு ஏற்றது.",
        "rainwaterHarvesting": "மழைநீர் சேகரிப்பு",
        "rainwaterHarvestingDesc": "எதிர்கால விவசாய பயன்பாட்டிற்கு மழைநீரை சேகரித்தல்.",
        "fertilizerNutrientGuide": "உரம் மற்றும் ஊட்டச்சத்து வழிகாட்டி",
        "fertilizerNutrientDesc": "அதிக விளைச்சலுக்கு உகந்த ஊட்டச்சத்து.",
        "npkBalance": "NPK சமநிலை",
        "npkBalanceDesc": "நைட்ரஜன், பாஸ்பரஸ் மற்றும் பொட்டாசியம் தேவைகளைப் புரிந்துகொள்ளுதல்.",
        "nutrientDeficiency": "ஊட்டச்சத்து குறைபாடு",
        "nutrientDeficiencyDesc": "தாவர ஊட்டச்சத்து சிக்கல்களைக் கண்டறிந்து சரிசெய்தல்.",
        "farmMachineryGuide": "பண்ணை இயந்திர வழிகாட்டி",
        "farmMachineryDesc": "நவீன பண்ணை உபகரணங்களுக்கான இயக்க வழிமுறைகள்.",
        "seedDrillInstr": "விதை துளையிடும் கருவி வழிமுறைகள்",
        "seedDrillDesc": "சீரான ஆழத்தில் துல்லியமாக விதைத்தல்.",
        "harvesterInstr": "அறுவடை இயந்திர வழிமுறைகள்",
        "harvesterDesc": "ஒரே கட்டத்தில் திறமையான அறுவடை மற்றும் போரடித்தல்.",
        "sprayerInstr": "தெளிப்பான் வழிமுறைகள்",
        "sprayerDesc": "பூச்சிக்கொல்லிகள் மற்றும் உரங்களை சீராக தெளித்தல்.",
        "extremeWeatherAlerts": "தீவிர வானிலை எச்சரிக்கைகள்",
        "extremeWeatherDesc": "புயல், வெப்ப அலைகளுக்கு உடனுக்குடன் எச்சரிக்கைகள்.",
        "weatherAlertTitle": "நடவடிக்கை தேவை!",
        "heatwaveWarning": "வெப்ப அலை எச்சரிக்கை: மண்ணை ஈரப்பதமாக வைத்திருங்கள்.",
        "frostWarning": "பனி எச்சரிக்கை: இளம் நாற்றுகளைப் பாதுகாக்கவும்.",
        "storagePostHarvest": "சேமிப்பு மற்றும் அறுவடைக்கு பிந்தைய வழிகாட்டி",
        "storagePostHarvestDesc": "சரியான சேமிப்புடன் லாபத்தை அதிகரிக்கவும்.",
        "grainStorage": "தானிய சேமிப்பு",
        "grainStorageDesc": "பூச்சிகளைத் தடுக்க நவீன சேமிப்புக் கிடங்குகள்.",
        "coldStorage": "குளிர்சாதன சேமிப்பு",
        "coldStorageDesc": "பழங்கள் மற்றும் காய்கறிகளின் ஆயுட்காலத்தை அதிகரிக்கவும்.",
        "nearbyAgriServices": "அருகிலுள்ள விவசாய சேவைகள்",
        "nearbyServicesDesc": " டிராக்டர் பழுதுபார்ப்பு, விதை கடைகள் மற்றும் மண்டிகளை கண்டறியவும்.",
        "cropVarietyDatabase": "பயிர் ரகங்கள் தரவுத்தளம்",
        "cropVarietyDesc": "அதிக விளைச்சல் தரும் பயிர் ரகங்களின் விவரங்கள்.",
        "farmTaskManager": "பண்ணை பணி மேலாளர்",
        "farmTaskDesc": "உங்கள் அன்றாட மற்றும் பருவக்கால பண்ணை பணிகளைத் திட்டமிடுங்கள்.",
        "mspGovtPrice": "MSP மற்றும் அரசு விலை தகவல்",
        "mspGovtPriceDesc": "உங்கள் பயிர்களுக்கான தற்போதைய குறைந்தபட்ச ஆதரவு விலை.",
        "mspWheat": "MSP கோதுமை (2024-25)",
        "mspPaddy": "MSP நெல் (2024-25)",
        "mspCotton": "MSP பருத்தி (2024-25)",
        "agriVideoLearning": "விவசாய வீடியோ கற்றல் மையம்",
        "agriVideoDesc": "நிபுணர் வீடியோக்கள் மூலம் விவசாயத்தில் தேர்ச்சி பெறுங்கள்.",
        "subsidyTracker": "விவசாய மானிய கண்காணிப்பு",
        "subsidyTrackerDesc": "உங்கள் விண்ணப்பம் এবং கட்டண நிலையைத் தெரிந்துகொள்ளுங்கள்.",
        "applicationStatus": "விண்ணப்ப நிலை",
        "paymentReceived": "கட்டணம் பெறப்பட்டது"
    },
    "Marathi": {
        "seasonalCropGuide": "हंगामी पीक मार्गदर्शक",
        "seasonalCropGuideDesc": "कोणत्या हंगामासाठी कोणते पीक सर्वोत्तम आहे ते जाणून घ्या.",
        "kharifCrops": "खरीप पिके",
        "kharifCropsDesc": "जून-जुलैमध्ये पेरणी, सप्टेंबर-ऑक्टोबरमध्ये कापणी. (उदा. भात, कापूस, मका)",
        "rabiCrops": "रब्बी पिके",
        "rabiCropsDesc": "ऑक्टोबर-डिसेंबरमध्ये पेरणी, मार्च-एप्रिलमध्ये कापणी. (उदा. गहू, मोहरी, हरभरा)",
        "zaidCrops": "जायद पिके",
        "zaidCropsDesc": "मार्च-जूनमध्ये पेरणी, उन्हाळी पिके. (उदा. टरबूज, काकडी)",
        "waterManagementGuide": "जल व्यवस्थापन मार्गदर्शक",
        "waterManagementDesc": "आधुनिक सिंचन आणि पाणी बचतीची तंत्रे.",
        "dripIrrigation": "ठिबक सिंचन",
        "dripIrrigationDesc": "थेट मुळांना पाणी, ५०% पर्यंत पाण्याची बचत.",
        "sprinklerIrrigation": "तुषार सिंचन",
        "sprinklerIrrigationDesc": "पावसासारखे पाणी, समान क्षेत्रासाठी उत्तम.",
        "rainwaterHarvesting": "पावसाचे पाणी साठवण",
        "rainwaterHarvestingDesc": "भविष्यातील शेतीसाठी पावसाचे पाणी साठवणे.",
        "fertilizerNutrientGuide": "खते आणि पोषक तत्वे मार्गदर्शक",
        "fertilizerNutrientDesc": "भरघोस उत्पादनासाठी योग्य पोषण.",
        "npkBalance": "एनपीके संतुलन",
        "npkBalanceDesc": "नत्र, स्फुरद आणि पालाश यांची गरज समजून घेणे.",
        "nutrientDeficiency": "पोषक तत्वांची कमतरता",
        "nutrientDeficiencyDesc": "झाडांमधील पोषक तत्वांच्या कमतरता ओळखा आणि दुरुस्त करा.",
        "farmMachineryGuide": "शेती यंत्रसामग्री मार्गदर्शक",
        "farmMachineryDesc": "आधुनिक शेती उपकरणांच्या वापराच्या सूचना.",
        "seedDrillInstr": "सीड ड्रिल सूचना",
        "seedDrillDesc": "समान खोलीवर अचूक बियाणे टोकणी.",
        "harvesterInstr": "हार्वेस्टर सूचना",
        "harvesterDesc": "एकाच टप्प्यात कार्यक्षम कापणी आणि मळणी.",
        "sprayerInstr": "स्प्रेअर सूचना",
        "sprayerDesc": "कीटकनाशके आणि खतांची समान फવારणी.",
        "extremeWeatherAlerts": "हवामान इशारा",
        "extremeWeatherDesc": "वादळ, उष्णतेची लाट आणि थंडीसाठी रिअल-टाइम अलर्ट.",
        "weatherAlertTitle": "कारवाई आवश्यक!",
        "heatwaveWarning": "उष्णतेची लाट इशारा: माती ओलावलेली ठेवा.",
        "frostWarning": "थंडीचा इशारा: तरुण रोपांचे संरक्षण करा.",
        "storagePostHarvest": "साठवणूक आणि कापणी पश्चात मार्गदर्शक",
        "storagePostHarvestDesc": "योग्य साठवणुकीसह नफा वाढवा.",
        "grainStorage": "अनाज साठवणूक",
        "grainStorageDesc": "कीकांपासून संरक्षणासाठी आधुनिक कोठारे.",
        "coldStorage": "कोल्ड स्टोरेज",
        "coldStorageDesc": "फळे आणि भाज्यांचे आयुष्य वाढवा.",
        "nearbyAgriServices": "जवळील कृषी सेवा",
        "nearbyServicesDesc": "ट्रॅक्टर दुरुस्ती, बियाणे भांडार आणि मंडई शोधा.",
        "cropVarietyDatabase": "पीक वाण डेटाबेस",
        "cropVarietyDesc": "जास्त उत्पन्न देणाऱ्या पीक वाणांची माहिती.",
        "farmTaskManager": "शेती कार्य व्यवस्थापक",
        "farmTaskDesc": "तुमच्या दैनंदিন आणि हंगामाच्या शेती कार्यांचे नियोजन करा.",
        "mspGovtPrice": "MSP आणि सरकारी दर माहिती",
        "mspGovtPriceDesc": "तुमच्या पिकांसाठी सध्याचे किमान आधारभूत दर.",
        "mspWheat": "MSP गहू (2024-25)",
        "mspPaddy": "MSP धान (2024-25)",
        "mspCotton": "MSP कापूस (2024-25)",
        "agriVideoLearning": "कृषी व्हिडिओ लर्निंग सेंटर",
        "agriVideoDesc": "तज्ज्ञांच्या व्हिडिओ ट्यूटोरियलसह शेतीमध्ये प्राविण्य मिळवा.",
        "subsidyTracker": "कृषी अनुदानाचा मागोवा",
        "subsidyTrackerDesc": "तुमच्या अर्जाची आणि पेमेंटची स्थिती पहा.",
        "applicationStatus": "अर्जाची स्थिती",
        "paymentReceived": "पेमेंट प्राप्त झाले"
    },
    "Gujarati": {
        "seasonalCropGuide": "મોસમી પાક માર્ગદર્શિકા",
        "seasonalCropGuideDesc": "જાણો કે દરેક ઋતુ માટે કયા પાક શ્રેષ્ઠ છે.",
        "kharifCrops": "ખરીફ પાક",
        "kharifCropsDesc": "જૂન-જુલાઈમાં વાવણી, સપ્ટેમ્બર-ઓક્ટોબરમાં લણણી. (દા.ત., ચોખા, કપાસ, મકાઈ)",
        "rabiCrops": "રવી પાક",
        "rabiCropsDesc": "ઓક્ટોબર-ડિસેમ્બરમાં વાવણી, માર્ચ-એપ્રિલમાં લણણી. (દા.ત., ઘઉં, રાયડો, ચણા)",
        "zaidCrops": "જાયદ પાક",
        "zaidCropsDesc": "માર્ચ-જૂનમાં વાવણી, ઉનાળુ પાક. (દા.ત., તરબૂચ, કાકડી)",
        "waterManagementGuide": "જળ વ્યવસ્થાપન માર્ગદર્શિકા",
        "waterManagementDesc": "આધુનિક પિયત અને પાણી બચતની પદ્ધતિઓ.",
        "dripIrrigation": "ટપક સિંચાઈ",
        "dripIrrigationDesc": "સીધું મૂળમાં પાણી, 50% સુધી પાણીની બચત.",
        "sprinklerIrrigation": "ફુવારા પિયત પદ્ધતિ",
        "sprinklerIrrigationDesc": "વરસાદની નકલ કરે છે, સમાન વિસ્તાર માટે ઉત્તમ.",
        "rainwaterHarvesting": "વરસાદી પાણીનો સંગ્રહ",
        "rainwaterHarvestingDesc": "ભવિષ્યની ખેતી માટે વરસાદી પાણીનો સંગ્રહ.",
        "fertilizerNutrientGuide": "ખાતર અને પોષક તત્વો માર્ગદર્શિકા",
        "fertilizerNutrientDesc": "ભરપૂર ઉત્પાદન માટે યોગ્ય પોષણ.",
        "npkBalance": "NPK સંતુલન",
        "npkBalanceDesc": "નાઈટ્રોજન, ફોસ્ફરસ અને પોટાશની જરૂરિયાત સમજવી.",
        "nutrientDeficiency": "પોષક તત્વોની ઉણપ",
        "nutrientDeficiencyDesc": "છોડના પોષક તત્વોની સમસ્યાઓ ઓળખો અને સુધારો.",
        "farmMachineryGuide": "ખેત મશીનરી માર્ગદર્શિકા",
        "farmMachineryDesc": "આધુનિક ખેત સાધનો માટે સંચાલન સૂચનાઓ.",
        "seedDrillInstr": "સીડ ડ્રિલ સૂચનાઓ",
        "seedDrillDesc": "સમાન ઊંડાઈ પર સચોટ બીજની વાવણી.",
        "harvesterInstr": "હાર્વેસ્ટર સૂચનાઓ",
        "harvesterDesc": "એક જ તબક્કે કાર્યક્ષમ લણણી અને મસળવાની પ્રક્રિયા.",
        "sprayerInstr": "સ્પ્રેયર સૂચનાઓ",
        "sprayerDesc": "જંતુનાશકો અને ખાતરોનો સમાન છંટકાવ.",
        "extremeWeatherAlerts": "હવામાન એલર્ટ",
        "extremeWeatherDesc": "વાવાઝોડા, હીટવેવ અને ઠંડી માટે રિયલ-ટાઇમ એલર્ટ.",
        "weatherAlertTitle": "કાર્યવાહી જરૂરી!",
        "heatwaveWarning": "હીટવેવ ચેતવણી: જમીનને ભેજવાળી રાખો.",
        "frostWarning": "ઠંડીની ચેતવણી: નાના છોડનું રક્ષણ કરો.",
        "storagePostHarvest": "સંગ્રહ અને લણણી પછીની માર્ગદર્શિકા",
        "storagePostHarvestDesc": "યોગ્ય સંગ્રહ સાથે નફો વધારો.",
        "grainStorage": "અનાજ સંગ્રહ",
        "grainStorageDesc": "જીવાત રોકવા માટે આધુનિક વખારો.",
        "coldStorage": "કોલ્ડ સ્ટોરેજ",
        "coldStorageDesc": "ફળો અને શાકભાજીનું આયુષ્ય વધારો.",
        "nearbyAgriServices": "નજીકની કૃષિ સેવાઓ",
        "nearbyServicesDesc": "ટ્રેક્ટર રીપેરીંગ, બીજ ભંડાર અને મંડીઓ શોધો.",
        "cropVarietyDatabase": "પાક વિવિધતા ડેટાબેઝ",
        "cropVarietyDesc": "વધુ ઉત્પાદન આપતી પાકની જાતોની વિગતવાર માહિતી.",
        "farmTaskManager": "ખેતી કાર્ય વ્યવસ્થાપક",
        "farmTaskDesc": "તમારા દૈનિક અને મોસમી ખેતી કાર્યોનું આયોજન કરો.",
        "mspGovtPrice": "MSP અને સરકારી ભાવની માહિતી",
        "mspGovtPriceDesc": "તમારા પાક માટે વર્તમાન લઘુત્તમ ટેકાના ભાવ.",
        "mspWheat": "MSP ઘઉં (2024-25)",
        "mspPaddy": "MSP ડાંગર (2024-25)",
        "mspCotton": "MSP કપાસ (2024-25)",
        "agriVideoLearning": "કૃષિ વિડિયો લર્નિંગ સેન્ટર",
        "agriVideoDesc": "નિષ્ણાત વિડિયો ટ્યુટોરિયલ્સ સાથે ખેતીમાં મહારત મેળવો.",
        "subsidyTracker": "કૃષિ સબસિડી ટ્રેકર",
        "subsidyTrackerDesc": "તમારી અરજી અને ચુકવણીની સ્થિતિ તપાસો.",
        "applicationStatus": "અરજીની સ્થિતિ",
        "paymentReceived": "ચુકવણી પ્રાપ્ત થઈ"
    },
    "Kannada": {
        "seasonalCropGuide": "ಕಾಲೋಚಿತ ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ",
        "seasonalCropGuideDesc": "ಪ್ರತಿ ಹಂಗಾಮಿಗೆ ಯಾವ ಬೆಳೆಗಳು ಉತ್ತಮವೆಂದು ತಿಳಿಯಿರಿ.",
        "kharifCrops": "ಖಾರೀಫ್ ಬೆಳೆಗಳು",
        "kharifCropsDesc": "ಜೂನ್-ಜುಲೈನಲ್ಲಿ ಬಿತ್ತನೆ, ಸೆಪ್ಟೆಂಬರ್-ಅಕ್ಟೋಬರ್ನಲ್ಲಿ ಕೊಯ್ಲು. (ಉದಾ. ಭತ್ತ, ಹತ್ತಿ, ಮೆಕ್ಕೆಜೋಳ)",
        "rabiCrops": "ರಬಿ ಬೆಳೆಗಳು",
        "rabiCropsDesc": "ಅಕ್ಟೋಬರ್-ಡಿಸೆಂಬರ್ನಲ್ಲಿ ಬಿತ್ತನೆ, ಮಾರ್ಚ್-ಏಪ್ರಿಲ್ನಲ್ಲಿ ಕೊಯ್ಲು. (ಉದಾ. ಗೋಧಿ, ಸಾಸಿವೆ, ಕಡಲೆ)",
        "zaidCrops": "ಜೈದ್ ಬೆಳೆಗಳು",
        "zaidCropsDesc": "ಮಾರ್ಚ್-ಜೂನ್ನಲ್ಲಿ ಬಿತ್ತನೆ, ಬೇಸಿಗೆ ಬೆಳೆಗಳು. (ಉದಾ. ಕಲ್ಲಂಗಡಿ, ಸೌತೆಕಾಯಿ)",
        "waterManagementGuide": "ನೀರಿನ ನಿರ್ವಹಣೆ ಮಾರ್ಗದರ್ಶಿ",
        "waterManagementDesc": "ಆಧುನಿಕ ನೀರಾವರಿ ಮತ್ತು ನೀರಿನ ಉಳಿತಾಯ ತಂತ್ರಗಳು.",
        "dripIrrigation": "ಹನಿ ನೀರಾವರಿ",
        "dripIrrigationDesc": "ನೇರವಾಗಿ ಬೇರುಗಳಿಗೆ ನೀರು, 50% ವರೆಗೆ ನೀರಿನ ಉಳಿತಾಯ.",
        "sprinklerIrrigation": "ತುಂತುರು ನೀರಾವರಿ",
        "sprinklerIrrigationDesc": "ಮಳೆಯಂತೆ ನೀರನ್ನು ಹನಿಸುತ್ತದೆ, ಸಮನಾದ ಪ್ರದೇಶಕ್ಕೆ ಸೂಕ್ತ.",
        "rainwaterHarvesting": "ಮಳೆನೀರು ಕೊಯ್ಲು",
        "rainwaterHarvestingDesc": "ಭವಿಷ್ಯದ ಕೃಷಿ ಬಳಕೆಗಾಗಿ ಮಳೆನೀರು ಸಂಗ್ರಹಿಸುವುದು.",
        "fertilizerNutrientGuide": "ಗೊಬ್ಬರ ಮತ್ತು ಪೋಷಕಾಂಶ ಮಾರ್ಗದರ್ಶಿ",
        "fertilizerNutrientDesc": "ಹೆಚ್ಚಿನ ಇಳುವರಿಗಾಗಿ ಸಮರ್ಪಕ ಪೋಷಣೆ.",
        "npkBalance": "NPK ಸಮತೋಲನ",
        "npkBalanceDesc": "ಸಾರಜನಕ, ರಂಜಕ ಮತ್ತು ಪೊಟ್ಯಾಸಿಯಮ್ ಅಗತ್ಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು.",
        "nutrientDeficiency": "ಪೋಷಕಾಂಶಗಳ ಕೊರತೆ",
        "nutrientDeficiencyDesc": "ಸಸ್ಯಗಳ ಪೋಷಕಾಂಶಗಳ ಸಮಸ್ಯೆಗಳನ್ನು ಗುರುತಿಸಿ ಮತ್ತು ಸರಿಪಡಿಸಿ.",
        "farmMachineryGuide": "ಕೃಷಿ ಯಂತ್ರೋಪಕರಣಗಳ ಮಾರ್ಗದರ್ಶಿ",
        "farmMachineryDesc": "ಆಧುನಿಕ ಕೃಷಿ ಉಪಕರಣಗಳ ಕಾರ್ಯಾಚರಣೆಯ ಸೂಚನೆಗಳು.",
        "seedDrillInstr": "ಸೀಡ್ ಡ್ರಿಲ್ ಸೂಚನೆಗಳು",
        "seedDrillDesc": "ಸರಿಯಾದ ಆಳದಲ್ಲಿ ನಿಖರವಾದ ಬೀಜ ಬಿತ್ತನೆ.",
        "harvesterInstr": "ಹಾರ್ವೆಸ್ಟರ್ ಸೂಚನೆಗಳು",
        "harvesterDesc": "ಒಂದೇ ಹಂತದಲ್ಲಿ ಕಾರ್ಯಕ್ಷಮತೆಯ ಕೊಯ್ಲು ಮತ್ತು ಒಕ್ಕಣೆ.",
        "sprayerInstr": "ಸ್ಪ್ರೇಯರ್ ಸೂಚನೆಗಳು",
        "sprayerDesc": "ಕೀಟನಾಶಕಗಳು ಮತ್ತು ಗೊಬ್ಬರಗಳ ಸಮನಾದ ಸಿಂಪಡಣೆ.",
        "extremeWeatherAlerts": "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು",
        "extremeWeatherDesc": "ಬಿರುಗಾಳಿ, ಬಿಸಿಗಾಳಿ ಮತ್ತು ಮಂಜಿನ ಬಗ್ಗೆ ಎಚ್ಚರಿಕೆಗಳು.",
        "weatherAlertTitle": "ಕ್ರಮ ಅಗತ್ಯವಿದೆ!",
        "heatwaveWarning": "ತೀವ್ರ ಬಿಸಿಗಾಳಿ ಎಚ್ಚರಿಕೆ: ಮಣ್ಣನ್ನು ತೇವವಾಗಿಡಿ.",
        "frostWarning": "ಮಂಜಿನ ಎಚ್ಚರಿಕೆ: ಎಳೆಯ ಸಸಿಗಳನ್ನು ರಕ್ಷಿಸಿ.",
        "storagePostHarvest": "ಸಂಗ್ರಹಣೆ ಮತ್ತು ಕೊಯ್ಲಿನ ನಂತರದ ಮಾರ್ಗದರ್ಶಿ",
        "storagePostHarvestDesc": "ಸರಿಯಾದ ಸಂಗ್ರಹಣೆಯೊಂದಿಗೆ ಲಾಭ ಹೆಚ್ಚಿಸಿ.",
        "grainStorage": "ಧಾನ್ಯ ಸಂಗ್ರಹಣೆ",
        "grainStorageDesc": "ಕೀಟಗಳನ್ನು ತಡೆಗಟ್ಟಲು ಆಧುನಿಕ ಗೋದಾಮುಗಳು.",
        "coldStorage": "ಕೋಲ್ಡ್ ಸ್ಟೋರೇಜ್",
        "coldStorageDesc": "ಹಣ್ಣು ಮತ್ತು ತರಕಾರಿಗಳ ಬಾಳಿಕೆಯನ್ನು ಹೆಚ್ಚಿಸಿ.",
        "nearbyAgriServices": "ಹತ್ತಿರದ ಕೃಷಿ ಸೇವೆಗಳು",
        "nearbyServicesDesc": "ಟ್ರಾಕ್ಟರ್ ದುರಸ್ತಿ, ಬೀಜದ ಮಳಿಗೆ ಮತ್ತು ಮಂಡಿಗಳನ್ನು ಹುಡುಕಿ.",
        "cropVarietyDatabase": "ಬೆಳೆ ತಳಿಗಳ ದತ್ತಸಂಚಯ",
        "cropVarietyDesc": "ಹೆಚ್ಚಿನ ಇಳುವರಿ ನೀಡುವ ಬೆಳೆ ತಳಿಗಳ ವಿವರಣೆ.",
        "farmTaskManager": "ಕೃಷಿ ಕಾರ್ಯ ವ್ಯವಸ್ಥಾಪಕ",
        "farmTaskDesc": "ನಿಮ್ಮ ದೈನಂದಿನ ಮತ್ತು ಹಂಗಾಮಿನ ಕೃಷಿ ಕಾರ್ಯಗಳನ್ನು ಯೋಜಿಸಿ.",
        "mspGovtPrice": "MSP ಮತ್ತು ಸರ್ಕಾರಿ ಬೆಲೆ ಮಾಹಿತಿ",
        "mspGovtPriceDesc": "ನಿಮ್ಮ ಬೆಳೆಗಳಿಗೆ ಈಗಿನ ಕನಿಷ್ಠ ಬೆಂಬಲ ಬೆಲೆ.",
        "mspWheat": "MSP ಗೋಧಿ (2024-25)",
        "mspPaddy": "MSP ಭತ್ತ (2024-25)",
        "mspCotton": "MSP ಹತ್ತಿ (2024-25)",
        "agriVideoLearning": "ಕೃಷಿ ವಿಡಿಯೋ ಕಲಿಕಾ ಕೇಂದ್ರ",
        "agriVideoDesc": "ತಜ್ಞರ ವಿಡಿಯೋಗಳ ಮೂಲಕ ಕೃಷಿಯಲ್ಲಿ ಪರಿಣಿತಿ ಪಡೆಯಿರಿ.",
        "subsidyTracker": "ಕೃಷಿ ಸಬ್ಸಿಡಿ ಟ್ರ್ಯಾಕರ್",
        "subsidyTrackerDesc": "ನಿಮ್ಮ ಅರ್ಜಿ ಮತ್ತು ಪಾವತಿ ಸ್ಥಿತಿಯನ್ನು ಗಮನಿಸಿ.",
        "applicationStatus": "ಅರ್ಜಿ ಸ್ಥಿತಿ",
        "paymentReceived": "ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ"
    },
    "Malayalam": {
        "seasonalCropGuide": "സീസണൽ വിള ഗൈഡ്",
        "seasonalCropGuideDesc": "ഓരോ സീസണിലും ഏത് വിളകളാണ് നല്ലതെന്ന് കണ്ടെത്തുക.",
        "kharifCrops": "ഖാരിഫ് വിളകൾ",
        "kharifCropsDesc": "ജൂൺ-ജൂലൈ മാസങ്ങളിൽ വിതച്ച് സെപ്റ്റംബർ-ഒക്ടോബറിൽ വിളവെടുക്കുന്നു. (ഉദാ: നെല്ല്, പരുത്തി, ചോളം)",
        "rabiCrops": "രവി വിളകൾ",
        "rabiCropsDesc": "ഒക്ടോബർ-ഡിസംബർ മാസങ്ങളിൽ വിതച്ച് മാർച്ച്-ഏപ്രിൽ മാസങ്ങളിൽ വിളവെടുക്കുന്നു. (ഉദാ: ഗോതമ്പ്, കടുക്, കടല)",
        "zaidCrops": "സെയ്ദ് വിളകൾ",
        "zaidCropsDesc": "മാർച്ച്-ജൂൺ മാസങ്ങളിൽ കൃഷി ചെയ്യുന്ന വേനൽക്കാല വിളകൾ. (ഉദാ: തണ്ണിമത്തൻ, വെള്ളരിക്ക)",
        "waterManagementGuide": "ജല പരിപാലന ഗൈഡ്",
        "waterManagementDesc": "നവീന ജലസേചന രീതികളും ജലസംരക്ഷണ വിദ്യകളും.",
        "dripIrrigation": "തുള്ളി നന",
        "dripIrrigationDesc": "വേരുകളിൽ നേരിട്ട് നനയ്ക്കുന്നു, 50% വരെ ജലം ലാഭിക്കാം.",
        "sprinklerIrrigation": "സ്പ്രിംഗ്ലർ നന",
        "sprinklerIrrigationDesc": "മഴ പോലെ നനയ്ക്കുന്നു, ഒരേപോലെ വെള്ളം ലഭിക്കാൻ ഉത്തമം.",
        "rainwaterHarvesting": "മഴവെള്ള സംഭരണം",
        "rainwaterHarvestingDesc": "കാർഷിക ആവശ്യങ്ങൾക്കായി മഴവെള്ളം ശേഖരിക്കുന്നു.",
        "fertilizerNutrientGuide": "വളവും പോഷകങ്ങളും ഗൈഡ്",
        "fertilizerNutrientDesc": "മെച്ചപ്പെട്ട വിളവിനായി ശരിയായ പോഷണം.",
        "npkBalance": "NPK സന്തുലിതാവസ്ഥ",
        "npkBalanceDesc": "നൈട്രജൻ, ഫോസ്ഫറസ്, പൊട്ടാസ്യം എന്നിവയുടെ അളവ് മനസ്സിലാക്കാം.",
        "nutrientDeficiency": "പോഷക കുറവ്",
        "nutrientDeficiencyDesc": "പോഷക കുറവുകൾ തിരിച്ചറിയുകയും പരിഹരിക്കുകയും ചെയ്യാം.",
        "farmMachineryGuide": "കാർഷിക യന്ത്ര ഗൈഡ്",
        "farmMachineryDesc": "നവീന കാർഷിക യന്ത്രങ്ങൾ പ്രവർത്തിപ്പിക്കാനുള്ള നിർദ്ദേശങ്ങൾ.",
        "seedDrillInstr": "സീഡ് ഡ്രിൽ നിർദ്ദേശങ്ങൾ",
        "seedDrillDesc": "കൃത്യമായ ആഴത്തിൽ വിത്ത് പാകാൻ സഹായിക്കുന്നു.",
        "harvesterInstr": "ഹാർവെസ്റ്റർ നിർദ്ദേശങ്ങൾ",
        "harvesterDesc": "ഒരേ സമയം കൊയ്ത്തും മെതിയും നടത്തുന്നു.",
        "sprayerInstr": "സ്പ്രെയർ നിർദ്ദേശങ്ങൾ",
        "sprayerDesc": "കീടനാശിനികളും വളങ്ങളും ഒരേപോലെ തളിക്കാൻ സഹായിക്കുന്നു.",
        "extremeWeatherAlerts": "കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ",
        "extremeWeatherDesc": "ചുഴലിക്കാറ്റ്, ഉഷ്ണതരംഗം എന്നിവയെക്കുറിച്ചുള്ള അറിയിപ്പുകൾ.",
        "weatherAlertTitle": "ശ്രദ്ധിക്കുക!",
        "heatwaveWarning": "ഉഷ്ണതരംഗം: മണ്ണിന്റെ ഈർപ്പം നിലനിർത്തുക.",
        "frostWarning": "മഞ്ഞു വീഴ്ച: ചെറിയ തൈകളെ സംരക്ഷിക്കുക.",
        "storagePostHarvest": "സംഭരണ മാർഗ്ഗനിർദ്ദേശങ്ങൾ",
        "storagePostHarvestDesc": "ശരിയായ സംഭരണത്തിലൂടെ ലാഭം വർദ്ധിപ്പിക്കാം.",
        "grainStorage": "ധാന്യ സംഭരണം",
        "grainStorageDesc": "കീടങ്ങളിൽ നിന്ന് സംരക്ഷിക്കാൻ ആധുനിക സംഭരണ രീതികൾ.",
        "coldStorage": "കോൾഡ് സ്റ്റോറേജ്",
        "coldStorageDesc": "പഴങ്ങളുടെയും പച്ചക്കറികളുടെയും ആയുസ്സ് വർദ്ധിപ്പിക്കുക.",
        "nearbyAgriServices": "സമീപത്തെ സേവനങ്ങൾ",
        "nearbyServicesDesc": "ട്രാക്ടർ വർക്ക്ഷോപ്പ്, വിത്ത് കടകൾ തുടങ്ങിയവ കണ്ടെത്തുക.",
        "cropVarietyDatabase": "വിളകളുടെ ഡാറ്റാബേസ്",
        "cropVarietyDesc": "മെച്ചപ്പെട്ട വിളവ് നൽകുന്ന ഇനങ്ങളെക്കുറിച്ചുള്ള വിവരങ്ങൾ.",
        "farmTaskManager": "ഫാം ടാസ്ക് മാനേജർ",
        "farmTaskDesc": "പിസ ദിവസത്തെയും സീസണിലെയും ജോലികൾ ക്രമീകരിക്കുക.",
        "mspGovtPrice": "താങ്ങുവിലയും സർക്കാർ വിലയും",
        "mspGovtPriceDesc": "വിളകളുടെ നിലവിലെ താങ്ങുവില അറിയാം.",
        "mspWheat": "ഗോതമ്പ് താങ്ങുവില (2024-25)",
        "mspPaddy": "നെല്ല് താങ്ങുവില (2024-25)",
        "mspCotton": "പരുത്തി താങ്ങുവില (2024-25)",
        "agriVideoLearning": "അഗ്രി വീഡിയോ ലേണിംഗ് സെന്റർ",
        "agriVideoDesc": "വീഡിയോ ട്യൂട്ടോറിയലിലൂടെ കൃഷി പഠിക്കാം.",
        "subsidyTracker": "സബ്സിഡി ട്രാക്കർ",
        "subsidyTrackerDesc": "അപേക്ഷയുടെയും പെയ്മെന്റത്തിന്റെയും നില അറിയാം.",
        "applicationStatus": "അപേക്ഷയുടെ നില",
        "paymentReceived": "പെയ്മെന്റ് ലഭിച്ചു"
    },
    "Punjabi": {
        "seasonalCropGuide": "ਮੌਸਮੀ ਫਸਲ ਗਾਈਡ",
        "seasonalCropGuideDesc": "ਪਤਾ ਕਰੋ ਕਿ ਹਰੇਕ ਸੀਜ਼ਨ ਲਈ ਕਿਹੜੀਆਂ ਫਸਲਾਂ ਸਭ ਤੋਂ ਵਧੀਆ ਹਨ।",
        "kharifCrops": "ਖਰੀਫ ਦੀਆਂ ਫਸਲਾਂ",
        "kharifCropsDesc": "ਜੂਨ-ਜੁਲਾਈ ਵਿੱਚ ਬੀਜੀ ਗਈ, ਸਤੰਬਰ-ਅਕਤੂਬਰ ਵਿੱਚ ਕੱਟੀ ਗਈ। (ਜਿਵੇਂ ਚਾਵਲ, ਕਪਾਹ, ਮੱਕੀ)",
        "rabiCrops": "ਰਬੀ ਦੀਆਂ ਫਸਲਾਂ",
        "rabiCropsDesc": "ਅਕਤੂਬਰ-ਦਸੰਬਰ ਵਿੱਚ ਬੀਜੀ ਗਈ, ਮਾਰਚ-ਅਪ੍ਰੈਲ ਵਿੱਚ ਕੱਟੀ ਗਈ। (ਜਿਵੇਂ ਕਣਕ, ਸਰ੍ਹੋਂ, ਛੋਲੇ)",
        "zaidCrops": "ਜ਼ਾਇਦ ਦੀਆਂ ਫਸਲਾਂ",
        "zaidCropsDesc": "ਮਾਰਚ-ਜੂਨ ਵਿੱਚ ਬੀਜੀ ਗਈ, ਗਰਮੀਆਂ ਦੀਆਂ ਫਸਲਾਂ। (ਜਿਵੇਂ ਤਰਬੂਜ, ਖੀਰਾ)",
        "waterManagementGuide": "ਜਲ ਪ੍ਰਬੰਧਨ ਗਾਈਡ",
        "waterManagementDesc": "ਆਧੁਨਿਕ ਸਿੰਚਾਈ ਅਤੇ ਪਾਣੀ ਦੀ ਬਚਤ ਦੀਆਂ ਤਕਨੀਕਾਂ।",
        "dripIrrigation": "ਡਰਿੱਪ ਸਿੰਚਾਈ",
        "dripIrrigationDesc": "ਸਿੱਧੇ ਜੜ੍ਹਾਂ ਵਿੱਚ ਪਾਣੀ, 50% ਤੱਕ ਪਾਣੀ ਦੀ ਬਚਤ।",
        "sprinklerIrrigation": "ਫੁਹਾਰਾ ਸਿੰਚਾਈ",
        "sprinklerIrrigationDesc": "ਮੀਂਹ ਵਰਗੀ ਸਿੰਚਾਈ, ਇੱਕਸਾਰ ਕਵਰੇਜ ਲਈ ਵਧੀਆ।",
        "rainwaterHarvesting": "ਬਰਸਾਤੀ ਪਾਣੀ ਦੀ ਸੰਭਾਲ",
        "rainwaterHarvestingDesc": "ਭਵਿੱਖ ਦੀ ਖੇਤੀ ਲਈ ਮੀਂਹ ਦੇ ਪਾਣੀ ਨੂੰ ਇਕੱਠਾ ਕਰਨਾ।",
        "fertilizerNutrientGuide": "ਖਾਦ ਅਤੇ ਪੋਸ਼ਟਿਕ ਤੱਤ ਗਾਈਡ",
        "fertilizerNutrientDesc": "ਵਧੀਆ ਝਾੜ ਲਈ ਸਹੀ ਪੋਸ਼ਣ।",
        "npkBalance": "NPK ਸੰਤੁલਨ",
        "npkBalanceDesc": "ਨਾਈਟ੍ਰੋਜਨ, ਫਾਸਫੋਰਸ ਅਤੇ ਪੋਟਾਸ਼ੀਅਮ ਦੀਆਂ ਲੋੜਾਂ ਨੂੰ ਸਮਝਣਾ।",
        "nutrientDeficiency": "ਪੋਸ਼ਟਿਕ ਤੱਤਾਂ ਦੀ ਕਮੀ",
        "nutrientDeficiencyDesc": "ਪੌਦਿਆਂ ਵਿੱਚ ਪੋਸ਼ਟਿਕ ਤੱਤਾਂ ਦੀ ਕਮੀ ਦੀ ਪਛਾਣ ਕਰੋ।",
        "farmMachineryGuide": "ਖੇਤੀ ਮਸ਼ੀਨਰੀ ਗਾਈਡ",
        "farmMachineryDesc": "ਖੇਤੀਬਾੜੀ ਦੇ ਆਧੁਨਿਕ ਸੰਦਾਂ ਦੀ ਵਰਤੋਂ ਦੇ ਨਿਰਦੇਸ਼।",
        "seedDrillInstr": "ਸੀਡ ਡ੍ਰਿਲ ਨਿਰਦੇਸ਼",
        "seedDrillDesc": "ਸਹੀ ਡੂੰਘਾਈ 'ਤੇ ਬੀਜਾਂ ਦੀ ਬਿਜਾਈ।",
        "harvesterInstr": "ਹਾਰਵੈਸਟਰ ਨਿਰਦੇਸ਼",
        "harvesterDesc": "ਕਟਾਈ ਅਤੇ ਗਹਾਈ ਦਾ ਕੁਸ਼ਲ ਤਰੀਕਾ।",
        "sprayerInstr": "ਸਪਰੇਅਰ ਨਿਰਦੇਸ਼",
        "sprayerDesc": "ਕੀਟਨਾਸ਼ਕਾਂ ਅਤੇ ਖਾਦਾਂ ਦਾ ਇੱਕਸਾਰ ਛਿੜਕਾਅ।",
        "extremeWeatherAlerts": "ਮੌਸਮ ਦੀ ਚੇਤਾਵਨੀ",
        "extremeWeatherDesc": "ਤੂਫਾਨ, ਲੂ ਅਤੇ ਕੋਰੇ ਬਾਰੇ ਤਾਜ਼ਾ ਜਾਣਕਾਰੀ।",
        "weatherAlertTitle": "ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਹੈ!",
        "heatwaveWarning": "ਲੂ ਦੀ ਚੇਤਾਵਨੀ: ਮਿੱਟੀ ਵਿੱਚ ਨਮੀ ਬਣਾਈ ਰੱਖੋ।",
        "frostWarning": "ਕੋਰੇ ਦੀ ਚੇਤਾਵਨੀ: ਨਵੀਆਂ ਫਸਲਾਂ ਨੂੰ ਬਚਾਓ।",
        "storagePostHarvest": "ਭੰਡਾਰਨ ਅਤੇ ਕਟਾਈ ਤੋਂ ਬਾਅਦ ਦੀ ਗਾਈਡ",
        "storagePostHarvestDesc": "ਸਹੀ ਭੰਡਾਰਨ ਨਾਲ ਮੁਨਾਫਾ ਵਧਾਓ।",
        "grainStorage": "ਅਨਾਜ ਭੰਡਾਰਨ",
        "grainStorageDesc": "ਕੀੜਿਆਂ ਤੋਂ ਬਚਾਅ ਲਈ ਆਧੁਨਿਕ ਗੋਦਾਮ।",
        "coldStorage": "ਕੋਲਡ ਸਟੋਰੇਜ",
        "coldStorageDesc": "ਫਲਾਂ ਅਤੇ ਸਬਜ਼ੀਆਂ ਦੀ ਤਾਜ਼ਗੀ ਬਰਕਰਾਰ ਰੱਖੋ।",
        "nearbyAgriServices": "ਨੇੜਲੀਆਂ ਖੇਤੀ ਸੇਵਾਵਾਂ",
        "nearbyServicesDesc": "ਟਰੈਕਟਰ ਮੁਰੰਮਤ, ਬੀਜਾਂ ਦੀਆਂ ਦੁਕਾਨਾਂ ਅਤੇ ਮੰਡੀਆਂ ਲੱਭੋ।",
        "cropVarietyDatabase": "ਫਸਲ ਦੀਆਂ ਕਿਸਮਾਂ ਦਾ ਡੇਟਾਬੇਸ",
        "cropVarietyDesc": "ਵੱਧ ਝਾੜ ਦੇਣ ਵਾਲੀਆਂ ਫਸਲਾਂ ਦੀਆਂ ਕਿਸਮਾਂ ਦੀ ਜਾਣਕਾਰੀ।",
        "farmTaskManager": "ਖੇਤੀ ਕਾਰਜ ਪ੍ਰਬੰਧਕ",
        "farmTaskDesc": "ਆਪਣੀਆਂ ਰੋਜ਼ਾਨਾ ਅਤੇ ਮੌਸਮੀ ਗਤੀਵਿਧੀਆਂ ਦੀ ਯੋਜನಾ ਬਣਾਓ।",
        "mspGovtPrice": "MSP ਅਤੇ ਸਰਕਾਰੀ ਕੀਮਤਾਂ",
        "mspGovtPriceDesc": "ਤੁਹਾਡੀਆਂ ਫਸਲਾਂ ਲਈ ਮੌਜੂਦਾ ਘੱਟੋ-ਘੱਟ ਸਮਰਥਨ ਮੁੱਲ।",
        "mspWheat": "MSP ਕਣਕ (2024-25)",
        "mspPaddy": "MSP ਝੋਨਾ (2024-25)",
        "mspCotton": "MSP ਕਪਾਹ (2024-25)",
        "agriVideoLearning": "ਖੇਤੀ ਵੀਡੀਓ ਲਰਨਿੰਗ ਸੈਂਟਰ",
        "agriVideoDesc": "ਮਾਹਰ ਵੀਡੀਓਜ਼ ਰਾਹੀਂ ਖੇਤੀਬਾੜੀ ਸਿੱਖੋ।",
        "subsidyTracker": "ਖੇਤੀਬਾੜੀ ਸਬਸਿಡಿ ਟ੍ਰੈਕਰ",
        "subsidyTrackerDesc": "ਆਪਣੀ ਅਰਜ਼ੀ ਅਤੇ ਭੁਗਤਾਨ ਦੀ ਸਥਿਤੀ ਦੇਖੋ।",
        "applicationStatus": "ਅਰਜ਼ੀ ਦੀ ਸਥਿਤੀ",
        "paymentReceived": "ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਹੋਇਆ"
    },
    "Bangla": {
        "seasonalCropGuide": "মৌসুমী ফসল নির্দেশিকা",
        "seasonalCropGuideDesc": "প্রতিটি ঋতুর জন্য কোন ফসলগুলি সেরা তা আবিষ্কার করুন।",
        "kharifCrops": "খারিফ ফসল",
        "kharifCropsDesc": "জুন-জুলাই মাসে বপন করা হয়, সেপ্টেম্বর-অক্টোবর মাসে কাটা হয়। (যেমন ধান, তুলা, ভুট্টা)",
        "rabiCrops": "রবি ফসল",
        "rabiCropsDesc": "অক্টোবর-ডিসেম্বর মাসে বপন করা হয়, মার্চ-এপ্রিল মাসে কাটা হয়। (যেমন গম, সরিষা, ছোলা)",
        "zaidCrops": "জায়েদ ফসল",
        "zaidCropsDesc": "মার্চ-জুন মাসে বপন করা হয়, গ্রীষ্মকালীন ফসল। (যেমন তরমুজ, শসা)",
        "waterManagementGuide": "জল ব্যবস্থাপনা নির্দেশিকা",
        "waterManagementDesc": "আধুনিক সেচ এবং জল সাশ্রয় পদ্ধতি।",
        "dripIrrigation": "ড্রিপ সেচ",
        "dripIrrigationDesc": "সরাসরি শিকড়ে জল দেওয়া, ৫০% পর্যন্ত জল সাশ্রয় করে।",
        "sprinklerIrrigation": "স্প্রিঙ্কলার সেচ",
        "sprinklerIrrigationDesc": "বৃষ্টির মতো সেচ দেওয়া, সমান অঞ্চলের জন্য আদর্শ।",
        "rainwaterHarvesting": "বৃষ্টির জল ধারণ",
        "rainwaterHarvestingDesc": "ভবিষ্যতের কৃষি ব্যবহারের জন্য বৃষ্টির জল সংগ্রহ করা।",
        "fertilizerNutrientGuide": "সার ও পুষ্টি নির্দেশিকা",
        "fertilizerNutrientDesc": "উচ্চ ফলনশীল চাষের জন্য আদর্শ পুষ্টি।",
        "npkBalance": "NPK ভারসাম্য",
        "npkBalanceDesc": "নাইট্রোজেন, ফসফরাস এবং পটাশিয়ামের প্রয়োজনীয়তা বোঝা।",
        "nutrientDeficiency": "পুষ্টির অভাব",
        "nutrientDeficiencyDesc": "গাছের সাধারণ পুষ্টির সমস্যাগুলি চিহ্নিত করুন এবং সমাধান করুন।",
        "farmMachineryGuide": "খামার যন্ত্রপাতি নির্দেশিকা",
        "farmMachineryDesc": "আধুনিক কৃষি যন্ত্রপাতির পরিচালনা নির্দেশাবলী।",
        "seedDrillInstr": "বীজ বপন যন্ত্র নির্দেশিকা",
        "seedDrillDesc": "সঠিক গভীরতায় বীজের সুনির্দিষ্ট বপন।",
        "harvesterInstr": "হারভেস্টার নির্দেশিকা",
        "harvesterDesc": "একই ধাপে দক্ষ ফসল কাটা এবং মাড়াই।",
        "sprayerInstr": "স্প্রেয়ার নির্দেশিকা",
        "sprayerDesc": "কীটনাশক এবং সারের সমান প্রয়োগ।",
        "extremeWeatherAlerts": "চরম আবহাওয়া সতর্কবাণী",
        "extremeWeatherDesc": "ঝড়, তাপপ্রবাহ এবং কুয়াশার জন্য রিয়েল-টাইম সতর্কতা।",
        "weatherAlertTitle": "ব্যবস্থা নেওয়া প্রয়োজন!",
        "heatwaveWarning": "তীব্র তাপপ্রবাহ সতর্কতা: মাটি ভেজা রাখুন।",
        "frostWarning": "কুয়াশা সতর্কতা: কচি চারাদের রক্ষা করুন।",
        "storagePostHarvest": "সংরক্ষণ ও ফসল পরবর্তী নির্দেশিকা",
        "storagePostHarvestDesc": "সঠিক সংরক্ষণের মাধ্যমে লাভ বাড়ান।",
        "grainStorage": "শস্য সংরক্ষণ",
        "grainStorageDesc": "পোকা প্রতিরোধ করতে আধুনিক সংরক্ষণ ব্যবস্থা।",
        "coldStorage": "কোল্ড স্টোরেজ",
        "coldStorageDesc": "ফল ও সবজির সতেজতা দীর্ঘস্থায়ী করুন।",
        "nearbyAgriServices": "নিকটস্থ কৃষি পরিষেবা",
        "nearbyServicesDesc": "ট্রাক্টর মেরামত, বীজের দোকান এবং মন্ডির সন্ধান করুন।",
        "cropVarietyDatabase": "ফসল বৈচিত্র্য তথ্যভাণ্ডার",
        "cropVarietyDesc": "উচ্চ ফলনশীল ফসলের জাতের বিস্তারিত তথ্য।",
        "farmTaskManager": "খামার কাজ পরিচালক",
        "farmTaskDesc": "আপনার দৈনিক এবং মৌসুমী খামার কার্যক্রমগুলি সংগঠিত করুন।",
        "mspGovtPrice": "MSP ও সরকারি মূল্যের তথ্য",
        "mspGovtPriceDesc": "আপনার ফসলের বর্তমান ন্যূনতম সহায়ক মূল্য।",
        "mspWheat": "MSP গম (২০২৪-২৫)",
        "mspPaddy": "MSP ধান (২০২৪-২৫)",
        "mspCotton": "MSP তুলা (২০২৪-২৫)",
        "agriVideoLearning": "কৃষি ভিডিও লার্নিং সেন্টার",
        "agriVideoDesc": "বিশেষজ্ঞ ভিডিও টিউটোরিয়ালের মাধ্যমে চাষাবাদে দক্ষ হন।",
        "subsidyTracker": "কৃষি ভর্তুকি ট্র্যাকার",
        "subsidyTrackerDesc": "আপনার আবেদন এবং পেমেন্টের অবস্থা অনুসরণ করুন।",
        "applicationStatus": "আবেদনের অবস্থা",
        "paymentReceived": "পেমেন্ট প্রাপ্ত হয়েছে"
    }
}

file_path = "d:/Desktop Data/project/farmersapp/client/lib/LanguageContext.tsx"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# Iterate through each language and add the keys
for lang, keys in new_keys.items():
    if lang + ": {" in content:
        lang_start_pat = rf"{lang}:\s*{{"
        start_match = re.search(lang_start_pat, content)
        if start_match:
            insert_str = ""
            for k, v in keys.items():
                if f"{k}:" not in content[start_match.start():start_match.start() + 5000]:
                     insert_str += f'    {k}: "{v}",\n'
            
            if insert_str:
                content = content[:start_match.end()] + "\n" + insert_str + content[start_match.end():]

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Smart farming translations added successfully.")
