import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "English" | "Hindi" | "Telugu" | "Tamil" | "Marathi" | "Gujarati" | "Kannada" | "Malayalam" | "Punjabi" | "Bangla";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  English: {
    home: "Home",
    weather: "Weather",
    market: "Market",
    calendar: "Calendar",
    security: "Security",
    aiChat: "AI Chat",
    schemes: "Schemes",
    government: "Government",
    rent: "Rent",
    settings: "Settings",
    login: "Login",
    welcome: "Welcome back,",
    agriOverview: "Everything looks good for farming today. Here's your agricultural overview.",
    bookTractor: "Book a Tractor",
    viewAll: "View All",
    applyNow: "Apply Now",
    trackApp: "Track Applications",
    plantingCalendar: "Planting Calendar",
    weatherAnalysis: "Live Weather Analysis & Recommendations",
    marketPrices: "Live Market Prices",
    cropEstimator: "Crop Price Estimator",
    findSchemes: "Find Schemes for Your Location",
    growingGuide: "Growing Guide",
    viewGrowingGuide: "View Growing Guide",
    pestsAndDiseases: "Pest & Disease Management",
    officialServices: "One-Click Access to Official Government Services",
    yieldGrowth: "Yield Growth",
    nextRain: "Next Rain",
    whyAgriPath: "Why Choose AgriPath?",
    howItWorks: "How it Works",
    chooseEquipment: "Need Help Choosing the Right Equipment?",
    chatAgriAI: "Chat with AgriAI",
    availableSchemes: "Available Schemes",
    incomeSupport: "Income Support",
    riskProtection: "Risk Protection",
    stateSupport: "State Support",
    trackMyApps: "Track My Applications",
    appId: "Application ID",
    status: "Status",
    date: "Date",
    noApps: "No applications found.",
    browseSelect: "Browse & Select",
    bookInstantly: "Book Instantly",
    happyFarming: "Happy Farming",
    searchServices: "Search for a service...",
    kisanCallCenter: "Kisan Call Center",
    emailSupport: "Email Support",
    whatsappChat: "WhatsApp Chat",
    faq: "Frequently Asked Questions",
    howApplySchemes: "How to apply for schemes?",
    howRentEquipment: "How to rent equipment?",
    howDetectDisease: "How to detect crop disease?",
    howTrackApp: "How to track application?",
    emergency: "Emergency?",
    callNow: "Call Now",
    crop: "Crop",
    quantity: "Quantity",
    unit: "Unit",
    estimate: "Estimate",
    suitability: "Suitability",
    growingGuideRice: "Rice Growing Guide",
    growingGuideCotton: "Cotton Growing Guide",
    growingGuidePulses: "Pulses Growing Guide",
    priceEstimator: "Price Estimator",
    mandiRatesNear: "Mandi Rates Near You",
    selectCommodity: "Select Commodity",
    calculate: "Calculate",
    expectedValue: "Expected Market Value",
    plantingWindow: "Planting Window",
    harvestingWindow: "Harvesting Window",
    tasksThisMonth: "Tasks This Month",
    bookActivity: "Book Activity",
    bookingConfirmed: "Booking Confirmed",
    activityType: "Activity Type",

    supportPortal: "Support Portal",
    trackSupport: "Track Support Requests",
    newSupportRequest: "New Support Request",
    submitRequest: "Submit Request",
    marketDataUpdated: "Market Data Updated",
    appSubmitted: "Application Submitted",
    schemePmKisan: "PM-Kisan Samman Nidhi",
    benefitPmKisan: "₹6,000 / Year",
    eligPmKisan: "Small & Marginal Farmers",
    descPmKisan: "Income support of ₹6,000 per year in three equal installments to all landholding farmer families.",
    schemePmfby: "Pradhan Mantri Fasal Bima Yojana",
    benefitPmfby: "Crop Insurance",
    eligPmfby: "All Farmers",
    descPmfby: "Provides financial support to farmers suffering crop loss/damage arising out of natural calamities.",
    schemeYsr: "YSR Rythu Bharosa",
    benefitYsr: "₹13,500 / Year",
    eligYsr: "AP Farmers",
    descYsr: "Financial assistance to farmers in Andhra Pradesh for agricultural operations.",
    schemeSoilHealth: "Soil Health Card Scheme",
    benefitSoilHealth: "Free Soil Testing",
    eligSoilHealth: "All Landholders",
    descSoilHealth: "Informs farmers about the nutrient status of their soil and recommendations on dosage of nutrients.",
    scientificFarming: "Scientific Farming",
    statusActive: "Active",
    statusOpen: "Open",
    statusOngoing: "Ongoing",
    categoryLabel: "Category",
    eligibilityLabel: "Eligibility",
    eligibleForYou: "Eligible For You",
    totalSchemes: "Total Schemes",
    deadlineAlerts: "Deadline Alerts",
    pmKisanVerification: "PM-Kisan Verification",
    eKycDeadline: "Submit your e-KYC by Oct 31st.",
    cropInsuranceLabel: "Crop Insurance",
    cropInsuranceEnrollment: "Enrollment starts Nov 1st.",
    clickLocationSchemes: "Click the button belo