const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '../lib/i18n');
const languages = ['bn', 'gu', 'hi', 'kn', 'ml', 'mr', 'pa', 'ta', 'te'];

const translations = {
  "hi": {
    "cultivationCosts": "खेती की लागत",
    "hydraulicResource": "जल संसाधन",
    "fiscalParameters": "राजकोषीय पैरामीटर",
    "defineFinancialExposure": "अपने वित्तीय जोखिम को परिभाषित करें",
    "marketPriceQtl": "बाजार मूल्य (₹/क्विंटल)",
    "analyzeExposure": "जोखिम का विश्लेषण करें",
    "efficiencyRating": "दक्षता रेटिंग",
    "totalYield": "कुल उपज",
    "biomassCost": "बायोमास लागत",
    "supplementation": "पूरक",
    "humanCapex": "मानव पूंजीगत व्यय",
    "macroIntelBulletin": "मैक्रो इंटेलिजेंस बुलेटिन",
    "hydraulicConfiguration": "हाइड्रोलिक कॉन्फ़िगरेशन",
    "defineIrrigationMatrix": "सिंचाई मैट्रिक्स परिभाषित करें",
    "syncHydroCycle": "हाइड्रो साइकिल सिंक करें",
    "dailyHydricLoad": "दैनिक जल भार",
    "liters24Hr": "लीटर / 24 घंटे",
    "precipitationDepth": "वर्षा की गहराई",
    "mmPerSector": "मिमी प्रति सेक्टर",
    "hydraulicPhasing": "हाइड्रोलिक चरणबद्धता",
    "temporalWaterManagement": "अस्थायी जल प्रबंधन प्रोटोकॉल",
    "linkActive": "लिंक सक्रिय",
    "phase": "चरण",
    "sowing": "बुवाई",
    "tillering": "टिलरिंग",
    "heading": "हेडिंग",
    "flowering": "फूल आना",
    "dough": "डफ",
    "systemPhilosophy": "सिस्टम दर्शन",
    "empoweringFarmersWithMacro": "मैक्रो इंटेलिजेंस के साथ किसानों को सशक्त बनाना।",
    "interrogatingIsmigs": "सटीक हाइड्रोलिक मॉडलिंग और राजकोषीय जोखिम विश्लेषण देने के लिए ISMIGS डेटासेट का उपयोग।",
    "exportDataManifest": "डेटा मेनिफेस्ट निर्यात करें",
    "hydraulicLoad": "हाइड्रोलिक भार",
    "resourceOptimization": "संसाधन अनुकूलन",
    "fiscalExposure": "राजकोषीय जोखिम",
    "realTimeCapexTracking": "रियल-टाइम कैपेक्स ट्रैकिंग",
    "dataIntegrity": "डेटा अखंडता",
    "verifiedStateDatasets": "सत्यापित राज्य डेटासेट",
    "yieldIntelligence": "उपज इंटेलिजेंस",
    "neuralCropProjections": "न्यूरल क्रॉप प्रोजेक्शन",
    "ismigsResourceIntel": "ISMIGS संसाधन इंटेल",
    "agriIntelligenceDesc": "हाइड्रोलिक संसाधन प्रबंधन और खेती के वित्तीय अनुमानों के लिए सटीक कैलकुलेटर।"
  },
  "te": {
    "cultivationCosts": "సాగు ఖర్చులు",
    "hydraulicResource": "జల వనరులు",
    "fiscalParameters": "ఆర్థిక పారామితులు",
    "defineFinancialExposure": "మీ ఆర్థిక రిస్క్‌ను నిర్వచించండి",
    "marketPriceQtl": "మార్కెట్ ధర (₹/క్వింటాల్)",
    "analyzeExposure": "రిస్క్ విశ్లేషించండి",
    "efficiencyRating": "సామర్థ్య రేటింగ్",
    "totalYield": "మొత్తం దిగుబడి",
    "biomassCost": "బయోమాస్ ఖర్చు",
    "supplementation": "అదనపు పోషకాలు",
    "humanCapex": "మానవ మూలధన వ్యయం",
    "macroIntelBulletin": "మాక్రో ఇంటెలిజెన్స్ బులెటిన్",
    "hydraulicConfiguration": "జల నిర్వహణ ఆకృతీకరణ",
    "defineIrrigationMatrix": "నీటి పారుదల మ్యాట్రిక్స్‌ను నిర్వచించండి",
    "syncHydroCycle": "హైడ్రో సైకిల్ సమకాలీకరించండి",
    "dailyHydricLoad": "రోజువారీ నీటి అవసరం",
    "liters24Hr": "లీటర్లు / 24 గంటలు",
    "precipitationDepth": "వర్షపాతం లోతు",
    "mmPerSector": "మిమీ ప్రతి విభాగం",
    "hydraulicPhasing": "జల నిర్వహణ దశలు",
    "temporalWaterManagement": "కాలక్రమ నీటి నిర్వహణ ప్రోటోకాల్",
    "linkActive": "లింక్ సక్రియం",
    "phase": "దశ",
    "sowing": "విత్తడం",
    "tillering": "పిలకలు వేయడం",
    "heading": "వెన్ను రావడం",
    "flowering": "పూత దశ",
    "dough": "గింజ ముదిరే దశ",
    "systemPhilosophy": "వ్యవస్థ సిద్ధాంతం",
    "empoweringFarmersWithMacro": "మాక్రో ఇంటెలిజెన్స్‌తో రైతులకు సాధికారత.",
    "interrogatingIsmigs": "ఖచ్చితమైన జల నమూనాలు మరియు ఆర్థిక విశ్లేషణను అందించడానికి ISMIGS డేటాసెట్‌లను ఉపయోగించడం.",
    "exportDataManifest": "డేటా మేనిఫెస్ట్‌ను ఎగుమతి చేయండి",
    "hydraulicLoad": "జల భారం",
    "resourceOptimization": "వనరుల ఆప్టిమైజేషన్",
    "fiscalExposure": "ఆర్థిక రిస్క్",
    "realTimeCapexTracking": "రియల్ టైమ్ క్యాపెక్స్ ట్రాకింగ్",
    "dataIntegrity": "డేటా సమగ్రత",
    "verifiedStateDatasets": "ధృవీకరించబడిన రాష్ట్ర డేటాసెట్‌లు",
    "yieldIntelligence": "దిగుబడి ఇంటెలిజెన్స్",
    "neuralCropProjections": "న్యూరల్ క్రాప్ ప్రొజెక్షన్",
    "ismigsResourceIntel": "ISMIGS వనరుల ఇంటెల్",
    "agriIntelligenceDesc": "జల వనరుల నిర్వహణ మరియు సాగు ఆర్థిక అంచనాల కోసం ఖచ్చితమైన కాలిక్యులేటర్లు."
  },
  "bn": {
    "cultivationCosts": "চাষের খরচ",
    "hydraulicResource": "জল সম্পদ",
    "fiscalParameters": "আর্থিক পরামিতি",
    "defineFinancialExposure": "আপনার আর্থিক ঝুঁকি সংজ্ঞায়িত করুন",
    "marketPriceQtl": "বাজার মূল্য (₹/কুইন্টাল)",
    "analyzeExposure": "ঝুঁকি বিশ্লেষণ করুন",
    "efficiencyRating": "দক্ষতা রেটিং",
    "totalYield": "মোট ফলন",
    "biomassCost": "বায়োমাস খরচ",
    "supplementation": "পরিপূরক",
    "humanCapex": "মানব মূলধনী ব্যয়",
    "macroIntelBulletin": "ম্যাক্রো ইন্টেলিজেন্স বুলেটিন",
    "hydraulicConfiguration": "হাইড্রোলিক কনফিগারেশন",
    "defineIrrigationMatrix": "সেচ ম্যাট্রিক্স সংজ্ঞায়িত করুন",
    "syncHydroCycle": "হাইড্রো সাইকেল সিঙ্ক করুন",
    "dailyHydricLoad": "দৈনিক জল ভার",
    "liters24Hr": "লিটার / ২৪ ঘণ্টা",
    "precipitationDepth": "বৃষ্টিপাতের গভীরতা",
    "mmPerSector": "মিমি প্রতি সেক্টর",
    "hydraulicPhasing": "হাইড্রোলিক ফেজিং",
    "temporalWaterManagement": "অস্থায়ী জল ব্যবস্থাপনা প্রোটোকল",
    "linkActive": "লিঙ্ক সক্রিয়",
    "phase": "পর্যায়",
    "sowing": "বপন",
    "tillering": "টিলারিং",
    "heading": "হেডিং",
    "flowering": "ফুল আসা",
    "dough": "ডাফ",
    "systemPhilosophy": "সিস্টেম দর্শন",
    "empoweringFarmersWithMacro": "ম্যাক্রো ইন্টেলিজেন্স দিয়ে কৃষকদের ক্ষমতায়ন করা।",
    "interrogatingIsmigs": "নির্ভুল হাইড্রোলিক মডেলিং এবং আর্থিক ঝুঁকি বিশ্লেষণ প্রদানের জন্য ISMIGS ডেটাসেট ব্যবহার করা।",
    "exportDataManifest": "ডেটা ম্যানিফেস্ট রপ্তানি করুন",
    "hydraulicLoad": "হাইড্রোলিক ভার",
    "resourceOptimization": "সম্পদ অপ্টিমাইজেশন",
    "fiscalExposure": "আর্থিক ঝুঁকি",
    "realTimeCapexTracking": "রিয়েল-টাইম ক্যাপেক্স ট্র্যাকিং",
    "dataIntegrity": "ডেটা অখণ্ডতা",
    "verifiedStateDatasets": "যাচাইকৃত রাজ্য ডেটাসেট",
    "yieldIntelligence": "ফলন বুদ্ধিমত্তা",
    "neuralCropProjections": "নিউরাল শস্য প্রক্ষেপণ",
    "ismigsResourceIntel": "ISMIGS রিসোর্স ইন্টেল",
    "agriIntelligenceDesc": "জল সম্পদ ব্যবস্থাপনা এবং চাষের আর্থিক পূর্বাভাসের জন্য নির্ভুল ক্যালকুলেটর।"
  }
};

languages.forEach(lang => {
    const filePath = path.join(i18nDir, `${lang}.ts`);
    let content = fs.readFileSync(filePath, 'utf8');
    
    const langTrans = translations[lang] || translations['hi']; // Fallback to Hindi if not available, or I could leave as is

    for (const [key, val] of Object.entries(langTrans)) {
        const regex = new RegExp(`"${key}": ".*?"`, 'g');
        content = content.replace(regex, `"${key}": "${val}"`);
    }
    
    fs.writeFileSync(filePath, content);
    console.log(`Updated translations for ${lang}`);
});
