import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "English" | "Hindi" | "Telugu" | "Tamil" | "Marathi" | "Gujarati" | "Kannada" | "Malayalam" | "Punjabi" | "Bangla";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  English: {
    home: "Home",
    weather: "Weather",
    market: "Market",
    calendar: "Calendar",
    security: "Security",
    aiChat: "AI Chat",
    schemes: "Schemes",
    government: "Government",
    rent: "Rent",
    settings: "Settings",
    login: "Login",
    welcome: "Welcome back,",
    agriOverview: "Everything looks good for farming today. Here's your agricultural overview.",
    bookTractor: "Book a Tractor",
    viewAll: "View All",
    applyNow: "Apply Now",
    trackApp: "Track Applications",
    plantingCalendar: "Planting Calendar",
    weatherAnalysis: "Live Weather Analysis & Recommendations",
    marketPrices: "Live Market Prices",
    cropEstimator: "Crop Price Estimator",
    findSchemes: "Find Schemes for Your Location",
    growingGuide: "Growing Guide",
    viewGrowingGuide: "View Growing Guide",
    pestsAndDiseases: "Pest & Disease Management",
    officialServices: "One-Click Access to Official Government Services",
    yieldGrowth: "Yield Growth",
    nextRain: "Next Rain",
    whyAgriPath: "Why Choose AgriPath?",
    howItWorks: "How it Works",
    chooseEquipment: "Need Help Choosing the Right Equipment?",
    chatAgriAI: "Chat with AgriAI",
    availableSchemes: "Available Schemes",
    incomeSupport: "Income Support",
    riskProtection: "Risk Protection",
    stateSupport: "State Support",
    trackMyApps: "Track My Applications",
    appId: "Application ID",
    status: "Status",
    date: "Date",
    noApps: "No applications found.",
    browseSelect: "Browse & Select",
    bookInstantly: "Book Instantly",
    happyFarming: "Happy Farming",
    searchServices: "Search for a service...",
    kisanCallCenter: "Kisan Call Center",
    emailSupport: "Email Support",
    whatsappChat: "WhatsApp Chat",
    faq: "Frequently Asked Questions",
    howApplySchemes: "How to apply for schemes?",
    howRentEquipment: "How to rent equipment?",
    howDetectDisease: "How to detect crop disease?",
    howTrackApp: "How to track application?",
    emergency: "Emergency?",
    callNow: "Call Now",
    crop: "Crop",
    quantity: "Quantity",
    unit: "Unit",
    estimate: "Estimate",
    suitability: "Suitability",
    growingGuideRice: "Rice Growing Guide",
    growingGuideCotton: "Cotton Growing Guide",
    growingGuidePulses: "Pulses Growing Guide",
  },
  Telugu: {
    home: "హోమ్",
    weather: "వాతావరణం",
    market: "మార్కెట్",
    calendar: "క్యాలెండర్",
    security: "భద్రత",
    aiChat: "AI చాట్",
    schemes: "పథకాలు",
    government: "ప్రభుత్వం",
    rent: "అద్దె",
    settings: "సెట్టింగులు",
    login: "లాగిన్",
    welcome: "తిరిగి స్వాగతం,",
    agriOverview: "ఈరోజు వ్యవసాయానికి అంతా బాగుంది. ఇక్కడ మీ వ్యవసాయ అవలోకనం ఉంది.",
    bookTractor: "ట్రాక్టర్ బుక్ చేయండి",
    viewAll: "అన్నీ చూడండి",
    applyNow: "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    trackApp: "దరఖాస్తులను ట్రాక్ చేయండి",
    plantingCalendar: "నాటడం క్యాలెండర్",
    weatherAnalysis: "प्रत्यక్ష వాతావరణ విశ్లేషణ & సిఫార్సులు",
    marketPrices: "प्रत्यక్ష మార్కెట్ ధరలు",
    cropEstimator: "పంట ధర అంచనా వేసేది",
    findSchemes: "మీ స్థానం కోసం పథకాలను కనుగొనండి",
    growingGuide: "సాగు మార్గదర్శిని",
    viewGrowingGuide: "సాగు మార్గదర్శిని చూడండి",
    pestsAndDiseases: "కీటకాలు & వ్యాధుల నిర్వహణ",
    officialServices: "అధికారిక ప్రభుత్వ సేవలకు ఒకే క్లిక్ యాక్సెస్",
    yieldGrowth: "దిగుబడి పెరుగుదల",
    nextRain: "తదుపరి వర్షం",
    whyAgriPath: "AgriPath ఎందుకు ఎంచుకోవాలి?",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    chooseEquipment: "సరైన పరికరాలను ఎంచుకోవడానికి సహాయం కావాలా?",
    chatAgriAI: "AgriAI తో చాట్ చేయండి",
    availableSchemes: "అందుబాటులో ఉన్న పథకాలు",
    incomeSupport: "ఆదాయ మద్దతు",
    riskProtection: "ప్రమాద రక్షణ",
    stateSupport: "రాష్ట్ర మద్దతు",
    trackMyApps: "నా దరఖాస్తులను ట్రాక్ చేయండి",
    appId: "దరఖాస్తు ID",
    status: "స్థితి",
    date: "తేదీ",
    noApps: "దరఖాస్తులు ఏవీ కనుగొనబడలేదు.",
    browseSelect: "బ్రౌజ్ చేయండి & ఎంచుకోండి",
    bookInstantly: "తక్షణమే బుక్ చేయండి",
    happyFarming: "సంతోషకరమైన వ్యవసాయం",
    searchServices: "సేవ కోసం వెతకండి...",
    kisanCallCenter: "కిసాన్ కాల్ సెంటర్",
    emailSupport: "ఇమెయిల్ మద్దతు",
    whatsappChat: "వాట్సాప్ చాట్",
    faq: "తరచుగా అడిగే ప్రశ్నలు",
    howApplySchemes: "పథకాల కోసం ఎలా దరఖాస్తు చేయాలి?",
    howRentEquipment: "పరికరాలను అద్దెకు తీసుకోవడం ఎలా?",
    howDetectDisease: "పంట వ్యాధిని ఎలా గుర్తించాలి?",
    howTrackApp: "దరఖాస్తును ఎలా ట్రాక్ చేయాలి?",
    emergency: "అత్యవసరమా?",
    callNow: "ఇప్పుడే కాల్ చేయండి",
    crop: "పంట",
    quantity: "పరిమాణం",
    unit: "యూనిట్",
    estimate: "అంచనా",
    suitability: "అనుకూలత",
    growingGuideRice: "వరి సాగు మార్గదర్శిని",
    growingGuideCotton: "ప్రత్తి సాగు మార్గదర్శిని",
    growingGuidePulses: "పప్పు ధాన్యాల సాగు మార్గదర్శిని",
  },
  Hindi: {
    home: "होम",
    weather: "मौसम",
    market: "बाजार",
    calendar: "कैलेंडर",
    security: "सुरक्षा",
    aiChat: "AI चैट",
    schemes: "योजनाएं",
    government: "सरकार",
    rent: "किराया",
    settings: "सेटिङ्ग्ज़",
    login: "लॉगिन",
    welcome: "वापस स्वागत है,",
    agriOverview: "आज खेती के लिए सब कुछ अच्छा लग रहा है। यहाँ आपका कृषि अवलोकन है।",
    bookTractor: "ट्रैक्टर बुक करें",
    viewAll: "सभी देखें",
    applyNow: "अभी आवेदन करें",
    trackApp: "आवेदनों को ट्रैक करें",
    plantingCalendar: "बुवाई कैलेंडर",
    weatherAnalysis: "लाइव मौसम विश्लेषण और सिफारिशें",
    marketPrices: "लाइव बाजार कीमतें",
    cropEstimator: "फसल मूल्य अनुमानक",
    findSchemes: "अपने स्थान के लिए योजनाएं खोजें",
    growingGuide: "खेती गाइड",
    viewGrowingGuide: "खेती गाइड देखें",
    pestsAndDiseases: "कीट और रोग प्रबंधन",
    officialServices: "आधिकारिक सरकारी सेवाओं तक वन-क्लिक पहुंच",
    yieldGrowth: "उपज वृद्धि",
    nextRain: "अगली बारिश",
    whyAgriPath: "AgriPath क्यों चुनें?",
    howItWorks: "यह कैसे काम करता है",
    chooseEquipment: "सही उपकरण चुनने में मदद चाहिए?",
    chatAgriAI: "AgriAI के साथ चैट करें",
    availableSchemes: "उपलब्ध योजनाएं",
    incomeSupport: "आय सहायता",
    riskProtection: "जोखिम सुरक्षा",
    stateSupport: "राज्य सहायता",
    trackMyApps: "मेरे आवेदनों को ट्रैक करें",
    appId: "आवेदन आईडी",
    status: "स्थिति",
    date: "तारीख",
    noApps: "कोई आवेदन नहीं मिला।",
    browseSelect: "ब्राउज़ करें और चुनें",
    bookInstantly: "तुरंत बुक करें",
    happyFarming: "खुशहाल खेती",
    searchServices: "सेवा खोजें...",
    kisanCallCenter: "किसान कॉल सेंटर",
    emailSupport: "ईमेल सहायता",
    whatsappChat: "व्हाट्सएप चैट",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    howApplySchemes: "योजनाओं के लिए आवेदन कैसे करें?",
    howRentEquipment: "उपकरण किराए पर कैसे लें?",
    howDetectDisease: "फसल रोग का पता कैसे लगाएं?",
    howTrackApp: "आवेदन को कैसे ट्रैक करें?",
    emergency: "आपातकाल?",
    callNow: "अभी कॉल करें",
    crop: "फसल",
    quantity: "मात्रा",
    unit: "इकाई",
    estimate: "अनुमान",
    suitability: "उपयुक्तता",
    growingGuideRice: "चावल की खेती गाइड",
    growingGuideCotton: "कपास की खेती गाइड",
    growingGuidePulses: "दालों की खेती गाइड",
  },
  Tamil: {
    home: "முகப்பு",
    weather: "வானிலை",
    market: "சந்தை",
    calendar: "காலண்டர்",
    security: "பாதுகாப்பு",
    aiChat: "AI சாட்",
    schemes: "திட்டங்கள்",
    government: "அரசு",
    rent: "வாடகை",
    settings: "அமைப்புகள்",
    login: "உள்நுழை",
    welcome: "மீண்டும் வருக,",
    agriOverview: "இன்று விவசாயத்திற்கு எல்லாம் நன்றாக இருக்கிறது. இதோ உங்கள் விவசாய மேலோட்டம்.",
    bookTractor: "டிராக்டர் முன்பதிவு செய்க",
    viewAll: "அனைத்தையும் பார்க்க",
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    trackApp: "விண்ணப்பங்களைக் கண்காணிக்கவும்",
    plantingCalendar: "நடவு காலண்டர்",
    weatherAnalysis: "நேரடி வானிலை பகுப்பாய்வு மற்றும் பரிந்துரைகள்",
    marketPrices: "நேரடி சந்தை விலைகள்",
    cropEstimator: "பயிர் விலை மதிப்பீட்டாளர்",
    findSchemes: "உங்கள் இருப்பிடத்திற்கான திட்டங்களைக் கண்டறியவும்",
    growingGuide: "வளர்ப்பு வழிகாட்டி",
    viewGrowingGuide: "வளர்ப்பு வழிகாட்டியைப் பார்க்கவும்",
    pestsAndDiseases: "பூச்சி மற்றும் நோய் மேலாண்மை",
    officialServices: "அதிகாரப்பூர்வ அரசு சேவைகளுக்கான ஒரு கிளிக் அணுகல்",
    yieldGrowth: "விளைச்சல் வளர்ச்சி",
    nextRain: "அடுத்த மழை",
    whyAgriPath: "AgriPath ஐ ஏன் தேர்வு செய்ய வேண்டும்?",
    howItWorks: "இது எப்படி வேலை செய்கிறது",
    chooseEquipment: "சரியான உபகரணங்களைத் தேர்வு செய்ய உதவி தேவையா?",
    chatAgriAI: "AgriAI உடன் சாட் செய்யுங்கள்",
    availableSchemes: "கிடைக்கும் திட்டங்கள்",
    incomeSupport: "வருமான ஆதரவு",
    riskProtection: "ஆபத்து பாதுகாப்பு",
    stateSupport: "மாநில ஆதரவு",
    trackMyApps: "என் விண்ணப்பங்களைக் கண்காணிக்கவும்",
    appId: "விண்ணப்ப ஐடி",
    status: "நிலை",
    date: "தேதி",
    noApps: "விண்ணப்பங்கள் எதுவும் இல்லை.",
    browseSelect: "உலாவவும் மற்றும் தேர்ந்தெடுக்கவும்",
    bookInstantly: "உடனடியாக முன்பதிவு செய்யுங்கள்",
    happyFarming: "மகிழ்ச்சியான விவசாயம்",
    searchServices: "சேவையைத் தேடுங்கள்...",
    kisanCallCenter: "கிசான் கால் சென்டர்",
    emailSupport: "மின்னஞ்சல் ஆதரவு",
    whatsappChat: "வாட்ஸ்அப் சாட்",
    faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    howApplySchemes: "திட்டங்களுக்கு எப்படி விண்ணப்பிப்பது?",
    howRentEquipment: "உபகரணங்களை வாடகைக்கு எடுப்பது எப்படி?",
    howDetectDisease: "பயிர் நோயைக் கண்டறிவது எப்படி?",
    howTrackApp: "விண்ணப்பத்தை எப்படிக் கண்காணிப்பது?",
    emergency: "அவசரமா?",
    callNow: "இப்போது அழைக்கவும்",
    crop: "பயிர்",
    quantity: "அளவு",
    unit: "அலகு",
    estimate: "மதிப்பீடு",
    suitability: "பொருத்தம்",
    growingGuideRice: "நெல் வளர்ப்பு வழிகாட்டி",
    growingGuideCotton: "பருத்தி வளர்ப்பு வழிகாட்டி",
    growingGuidePulses: "பருப்பு வகைகள் வளர்ப்பு வழிகாட்டி",
  },
  Marathi: { home: "होम", weather: "हवामान", market: "बाजार", calendar: "कॅलेंडर", security: "सुरक्षा", aiChat: "AI चॅट", schemes: "योजना", government: "सरकार", rent: "भाडे", settings: "सेटिंग्ज", login: "लॉगिन", welcome: "परत स्वागत आहे," },
  Gujarati: { home: "હોમ", weather: "હવામાન", market: "બજાર", calendar: "કેલેન્ડર", security: "સુરક્ષા", aiChat: "AI ચેટ", schemes: "યોજનાઓ", government: "સરકાર", rent: "ભાડું", settings: "સેટિંગ્સ", login: "લોગિન", welcome: "સ્વાગત છે," },
  Kannada: {
    home: "ಮನೆ",
    weather: "ಹವಾಮಾನ",
    market: "ಮಾರುಕಟ್ಟೆ",
    calendar: "ಕ್ಯಾಲೆಂಡರ್",
    security: "ಭದ್ರತೆ",
    aiChat: "AI ಚಾಟ್",
    schemes: "ಯೋಜನೆಗಳು",
    government: "ಸರ್ಕಾರ",
    rent: "ಬಾಡಿಗೆ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    login: "ಲಾಗಿನ್",
    welcome: "ಮರಳಿ ಸ್ವಾಗತ,",
    agriOverview: "ಇಂದು ಕೃಷಿಗೆ ಎಲ್ಲವೂ ಚೆನ್ನಾಗಿ ಕಾಣುತ್ತಿದೆ. ನಿಮ್ಮ ಕೃಷಿ ಅವಲೋಕನ ಇಲ್ಲಿದೆ.",
    bookTractor: "ಟ್ರಾಕ್ಟರ್ ಬುಕ್ ಮಾಡಿ",
    viewAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    applyNow: "ಈಗಲೇ ಅನ್ವಯಿಸಿ",
    trackApp: "ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    plantingCalendar: "ನಾಟಿ ಕ್ಯಾಲೆಂಡರ್",
    weatherAnalysis: "ಲೈವ್ ಹವಾಮಾನ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಶಿಫಾರಸುಗಳು",
    marketPrices: "ಲೈವ್ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    cropEstimator: "ಬೆಳೆ ಬೆಲೆ ಅಂದಾಜುಗಾರ",
    findSchemes: "ನಿಮ್ಮ ಸ್ಥಳಕ್ಕಾಗಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    growingGuide: "ಬೆಳವಣಿಗೆಯ ಮಾರ್ಗದರ್ಶಿ",
    viewGrowingGuide: "ಬೆಳವಣಿಗೆಯ ಮಾರ್ಗದರ್ಶಿಯನ್ನು ನೋಡಿ",
    pestsAndDiseases: "ಕೀಟ ಮತ್ತು ರೋಗ ನಿರ್ವಹಣೆ",
    officialServices: "ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಸೇವೆಗಳಿಗೆ ಒಂದು ಕ್ಲಿಕ್ ಪ್ರವೇಶ",
    yieldGrowth: "ಇಳುವರಿ ಬೆಳವಣಿಗೆ",
    nextRain: "ಮುಂದಿನ ಮಳೆ",
    whyAgriPath: "AgriPath ಅನ್ನು ಏಕೆ ಆರಿಸಬೇಕು?",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    chooseEquipment: "ಸರಿಯಾದ ಉಪಕರಣಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಸಹಾಯ ಬೇಕೇ?",
    chatAgriAI: "AgriAI ನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    availableSchemes: "ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು",
    incomeSupport: "ಆದಾಯ ಬೆಂಬಲ",
    riskProtection: "ಅಪಾಯದ ರಕ್ಷಣೆ",
    stateSupport: "ರಾಜ್ಯ ಬೆಂಬಲ",
    trackMyApps: "ನನ್ನ ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    appId: "ಅರ್ಜಿ ID",
    status: "ಸ್ಥಿತಿ",
    date: "ದಿನಾಂಕ",
    noApps: "ಯಾವುದೇ ಅರ್ಜಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    browseSelect: "ಬ್ರೌಸ್ ಮಾಡಿ ಮತ್ತು ಆಯ್ಕೆ ಮಾಡಿ",
    bookInstantly: "ತಕ್ಷಣ ಬುಕ್ ಮಾಡಿ",
    happyFarming: "ಸಂತೋಷದ ಕೃಷಿ",
    searchServices: "ಸೇವೆಗಾಗಿ ಹುಡುಕಿ...",
    kisanCallCenter: "ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್",
    emailSupport: "ಇಮೇಲ್ ಬೆಂಬಲ",
    whatsappChat: "ವಾಟ್ಸಾಪ್ ಚಾಟ್",
    faq: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    howApplySchemes: "ಯೋಜನೆಗಳಿಗೆ ಅನ್ವಯಿಸುವುದು ಹೇಗೆ?",
    howRentEquipment: "ಉಪಕರಣಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯುವುದು ಹೇಗೆ?",
    howDetectDisease: "ಬೆಳೆ ರೋಗವನ್ನು ಪತ್ತೆ ಮಾಡುವುದು ಹೇಗೆ?",
    howTrackApp: "ಅರ್ಜಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುವುದು ಹೇಗೆ?",
    emergency: "ತುರ್ತು ಪರಿಸ್ಥಿತಿಯೇ?",
    callNow: "ಈಗಲೇ ಕರೆ ಮಾಡಿ",
    crop: "ಬೆಳೆ",
    quantity: "ಪ್ರಮಾಣ",
    unit: "ಘಟಕ",
    estimate: "ಅಂದಾಜು",
    suitability: "ಸೂಕ್ತತೆ",
    growingGuideRice: "ಭತ್ತದ ಬೆಳವణಿಗೆಯ ಮಾರ್ಗದರ್ಶಿ",
    growingGuideCotton: "ಹತ್ತಿ ಬೆಳವಣಿಗೆಯ ಮಾರ್ಗದರ್ಶಿ",
    growingGuidePulses: "ಬೇಳೆಕಾಳುಗಳ ಬೆಳವಣಿಗೆಯ ಮಾರ್ಗದರ್ಶಿ",
  },
  Malayalam: { home: "ഹോം", weather: "കാലാവസ്ഥ", market: "മാർക്കറ്റ്", calendar: "കലണ്ടർ", security: "സുരക്ഷ", aiChat: "AI ചാറ്റ്", schemes: "പദ്ധതികൾ", government: "സർക്കാർ", rent: "വാടക", settings: "ക്രമീകരണങ്ങൾ", login: "ലോഗിൻ", welcome: "സ്വാഗതം," },
  Punjabi: { home: "ਹੋਮ", weather: "ਮੌਸਮ", market: "ਮਾਰਕੀਟ", calendar: "ਕੈਲੰਡਰ", security: "ਸੁਰੱਖਿਆ", aiChat: "AI ਚੈਟ", schemes: "ਯੋਜਨਾਵਾਂ", government: "ਸਰਕਾਰ", rent: "ਕਿਰਾਇਆ", settings: "ਸੈਟਿੰਗਾਂ", login: "ਲੌਗਿਨ", welcome: "ਜੀ ਆਇਆਂ ਨੂੰ," },
  Bangla: { home: "হোম", weather: "আবহাওয়া", market: "বাজার", calendar: "ক্যালেন্ডার", security: "সুরক্ষা", aiChat: "AI চ্যাট", schemes: "প্রকল্প", government: "সরকার", rent: "ভাড়া", settings: "সেটিংস", login: "লগইন", welcome: "স্বাগতম," },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("techspark_lang");
    return (saved as Language) || "English";
  });

  useEffect(() => {
    localStorage.setItem("techspark_lang", language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations["English"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
